In [1]:
# !pip install ultralytics -q

In [7]:
import pandas as pd
import torch
from ultralytics import YOLO
import os
import yaml
import pandas as pd
from collections import Counter

print(torch.cuda.is_available())

True

In [ ]:
# Uncomment if running on Google Colab
# from google.colab import drive
# drive.mount('/content/drive')
# path = "/content/drive/MyDrive/pubmat-checker"

## Create YAML File

In [8]:


data = {
    "path": "./data",
    "train": "images/train",
    "val": "images/val",
    "test": "images/test",

    "names": {
        0: "NYC_Correct",
        1: "NYC_Incorrect",
        2: "BP_Correct",
        3: "BP_Incorrect",
        4: "SK_Correct",
        5: "SK_Incorrect",
        6: "YORP_Correct",
        7: "YORP_Incorrect",
    }

}
with open("./data.yaml", "w") as f:
    yaml.dump(data, f)

print("data.yaml file created.")

data.yaml file created.

In [13]:
import os
import yaml
from collections import Counter

data_yaml_path = "./data.yaml"

with open(data_yaml_path, "r") as f:
    data_config = yaml.safe_load(f)

base_path = data_config["path"]
class_names = data_config["names"]

image_dir = os.path.join(base_path, "images", "train")
label_dir = os.path.join(base_path, "labels", "train")

# collect files
image_stems = {
    os.path.splitext(f)[0]
    for f in os.listdir(image_dir)
    if f.lower().endswith((".png", ".jpg", ".jpeg", ".bmp"))
}

label_stems = {
    os.path.splitext(f)[0]
    for f in os.listdir(label_dir)
    if f.lower().endswith(".txt")
}

# check mismatches
errors = []

for stem in image_stems - label_stems:
    errors.append(f"Image has no label: {stem}")

for stem in label_stems - image_stems:
    errors.append(f"Label has no image: {stem}")

# count classes
class_counts = Counter()

for stem in label_stems:
    with open(os.path.join(label_dir, stem + ".txt")) as f:
        for line in f:
            parts = line.strip().split()
            if parts:
                class_counts[int(parts[0])] += 1

# print distribution
total = sum(class_counts.values())

print("\nTraining Set Class Distribution")
for class_id, count in sorted(class_counts.items()):
    name = class_names.get(class_id, f"Unknown {class_id}")
    pct = (count / total) * 100 if total else 0
    print(f"{name}: {count} ({pct:.1f}%)")

# print errors
print("\nData Check")
if errors:
    for e in errors:
        print("-", e)
else:
    print("No errors found. All images have corresponding labels and vice versa.")

Training Set Class Distribution
NYC_Correct: 596 (14.2%)
NYC_Incorrect: 517 (12.3%)
BP_Correct: 479 (11.4%)
BP_Incorrect: 629 (15.0%)
SK_Correct: 597 (14.2%)
SK_Incorrect: 396 (9.4%)
YORP_Correct: 609 (14.5%)
YORP_Incorrect: 372 (8.9%)

Data Check
No errors found. All images have corresponding labels and vice versa.

## Train YOLO Model

### Baseline

In [14]:
# Initialize pre-trained YOLO model
model = YOLO("yolov8n.pt")

model.train(
    data="./data.yaml",
    name="base_model",
    epochs=80,
    imgsz=640,
    batch=16,
    seed=42,              

    optimizer="AdamW",
    lr0=0.003,
    lrf=0.01,
    weight_decay=0.0005,
    warmup_epochs=3.0,

    patience=15,
    device=0,
    workers=2,
    cache=True,         
    amp=True,

    degrees=0.0,          # no rotation
    translate=0.05,       # slight movement
    scale=0.8,            # small variation only
    fliplr=0.0,           # no horizontal flip 
    flipud=0.0,
    mosaic=1.0,
    mixup=0.0             # avoid mixing correct/incorrect classes
)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 14.5MB/s 0.4s.4s<0.0s4s3s
New https://pypi.org/project/ultralytics/8.4.41 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=True, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=./data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=80, erasing=0.4, exist_ok=False, fliplr=0.0, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.003, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=base_model, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=15, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\base_model, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.8, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.05, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=8

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    752872  ultralytics.nn.modules.head.Detect           [8, 16, None, [64, 128, 256]]
Model summary: 130 layers, 3,012,408 parameters, 3,012,392 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 243.655.5 MB/s, size: 205.3 KB)
train: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\train... 1445 images, 139 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1445/1445 3.3Kit/s 0.4s0.1s
train: New cache created: C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\train.cache
WARNING cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
train: Caching images (1.3GB RAM): 100% ━━━━━━━━━━━━ 1445/1445 916.6it/s 1.6s0.0s
val: Fast image access  (ping: 0.20.1 ms, read: 245.422.8 MB/s, size: 259.7 KB)
val: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\val... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 1.4Kit/s 0.2s<0.0s
val: New cache created: C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\val.cache
WARNING cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.3GB RAM): 100% ━━━━━━━━━━━━ 334/334 641.6it/s 0.5s0.0s
optimizer: AdamW(lr=0.003, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\base_model\labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\base_model
Starting training for 80 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/80      1.99G      1.286      2.347      1.067         26        640: 100% ━━━━━━━━━━━━ 91/91 4.0it/s 22.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.0it/s 2.2s0.2s
                   all        334        992      0.497      0.655      0.551      0.404

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/80       2.4G       1.05      1.297     0.9805         23        640: 100% ━━━━━━━━━━━━ 91/91 4.9it/s 18.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.592       0.78      0.708       0.49

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/80      2.41G      1.002      1.168     0.9681         35        640: 100% ━━━━━━━━━━━━ 91/91 5.7it/s 16.0s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.714      0.766      0.787      0.571

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/80      2.41G     0.9237      1.023     0.9504         17        640: 100% ━━━━━━━━━━━━ 91/91 5.7it/s 16.1s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.716      0.766      0.801      0.615

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/80      2.41G     0.8831     0.9616      0.928         32        640: 100% ━━━━━━━━━━━━ 91/91 5.5it/s 16.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.744      0.806      0.844      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/80      2.41G     0.8293     0.8815     0.9158         38        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.765      0.804      0.832       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/80      2.41G     0.8135     0.8481     0.9123         25        640: 100% ━━━━━━━━━━━━ 91/91 5.7it/s 15.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.4it/s 1.7s0.2s
                   all        334        992      0.818      0.827      0.902      0.707

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/80      2.41G     0.7817      0.835     0.9083          8        640: 100% ━━━━━━━━━━━━ 91/91 5.7it/s 15.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.823      0.841      0.883      0.705

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/80      2.41G     0.7335     0.7697     0.8866         16        640: 100% ━━━━━━━━━━━━ 91/91 5.7it/s 15.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992       0.87      0.872      0.925      0.769

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/80      2.41G     0.7133     0.7463      0.885         10        640: 100% ━━━━━━━━━━━━ 91/91 5.7it/s 16.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.3it/s 1.7s0.2s
                   all        334        992      0.897      0.874      0.932      0.795

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/80      2.41G     0.7306     0.7255     0.8809         22        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.1it/s 1.8s0.2s
                   all        334        992      0.881      0.868      0.938       0.78

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/80      2.41G      0.708     0.7268     0.8797         47        640: 100% ━━━━━━━━━━━━ 91/91 5.3it/s 17.0s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.906       0.86      0.919      0.764

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/80      2.41G      0.698     0.7108     0.8734         37        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.7it/s 1.9s0.2s
                   all        334        992      0.911      0.881      0.937      0.796

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/80      2.41G     0.6783     0.6771     0.8782         30        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.9it/s 1.9s0.2s
                   all        334        992      0.832      0.845        0.9      0.766

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/80      2.41G     0.6711     0.6587     0.8703         18        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.917      0.891       0.95       0.82

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/80      2.41G     0.6634      0.656     0.8644         29        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.888      0.915      0.935      0.792

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/80      2.41G     0.6586     0.6509     0.8693         25        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.915      0.877      0.943      0.818

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/80      2.41G     0.6337      0.624     0.8612         39        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.887      0.911      0.948      0.824

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/80      2.41G     0.6147     0.5971     0.8583         26        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 17.0s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.9it/s 1.9s0.2s
                   all        334        992      0.909      0.921      0.954      0.835

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/80      2.41G      0.611      0.597     0.8573         29        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.8it/s 1.9s0.2s
                   all        334        992      0.928      0.923      0.958      0.827

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/80      2.41G     0.6176     0.5845     0.8566         21        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.9it/s 1.9s0.2s
                   all        334        992      0.906      0.917      0.954      0.846

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/80      2.41G     0.6039     0.5664     0.8571         26        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.1it/s 1.8s0.2s
                   all        334        992      0.932      0.911      0.955      0.843

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/80      2.41G     0.6036     0.5729     0.8556         13        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.901      0.902      0.947      0.839

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/80      2.41G     0.5881     0.5615      0.848         18        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.924      0.927       0.96      0.857

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/80      2.41G     0.5842     0.5493     0.8488         29        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.9it/s 1.9s0.2s
                   all        334        992      0.928      0.903      0.945      0.842

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/80      2.41G     0.5812     0.5368     0.8484         25        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992       0.95      0.922      0.963       0.87

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/80      2.41G     0.5869     0.5444     0.8507         27        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.913      0.902      0.952      0.838

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/80      2.41G     0.5535     0.5179     0.8468         26        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.945       0.93      0.961      0.882

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/80      2.41G     0.5466     0.5216     0.8436         35        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.936      0.897      0.954      0.857

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/80      2.41G     0.5434     0.5076     0.8401         17        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 17.0s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.926      0.939      0.964      0.875

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/80      2.41G     0.5584     0.5031       0.84         23        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.934      0.931      0.958      0.872

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/80      2.41G     0.5411     0.5038     0.8437         18        640: 100% ━━━━━━━━━━━━ 91/91 5.5it/s 16.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.9it/s 1.9s0.2s
                   all        334        992       0.95      0.917      0.963      0.875

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/80      2.41G     0.5414      0.497     0.8378         30        640: 100% ━━━━━━━━━━━━ 91/91 5.4it/s 16.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.1it/s 1.8s0.2s

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6, 7])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x00000236D4C33F50>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,     0.88095,     0.88095,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       ...,
       [          1,           1,           1, ...,     0.41232,     0.41232,           0],
       [          1,           1,           1, ...,     0.94839,     0.94839,           0],
       [          1,           1,           1, ...,     0.28296,     0.28296,           0]], shape=(8, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

In [15]:
base_model = YOLO("runs/detect/base_model/weights/best.pt")

### Tuning

In [16]:
# Re-initialize before tuning
model = YOLO("yolov8n.pt")

model.tune(
    data="./data.yaml",
    iterations=50,
    imgsz=640,
    batch=16,
    epochs=30,
    patience=10,
    optimizer="AdamW",
    plots=True,
    save=True
)

Tuner: Initialized Tuner instance with 'tune_dir=C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune'
Tuner:  Learn about tuning at https://docs.ultralytics.com/guides/hyperparameter-tuning
Tuner: Starting iteration 1/50 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'box': 7.5, 'cls': 0.5, 'cls_pw': 0.0, 'dfl': 1.5, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.0, 'cutmix': 0.0, 'copy_paste': 0.0, 'close_mosaic': 10}
ERROR training failure for hyperparameter tuning iteration 1
Command '['c:\\python313\\python.exe', '-m', 'ultralytics.cfg.__init__', 'train', 'task=detect', 'mode=train', 'model=yolov8n.pt', 'epochs=30', 'time=None', 'patience=10', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=None', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=True', 'optimizer=AdamW', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=10', 'resume=False', 'amp=True', 'fraction=1.0', 'profile=False', 'freeze=None', 'multi_scale=0.0', 'compile=False', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'end2end=None', 'source=None', 'vid_stride=1', 'stream_buffer=False', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'embed=None', 'show=False', 'save_frames=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'show_boxes=True', 'line_width=None', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=True', 'opset=None', 'workspace=None', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'cls_pw=0.0', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'rle=1.0', 'angle=1.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'bgr=0.0', 'mosaic=1.0', 'mixup=0.0', 'cutmix=0.0', 'copy_paste=0.0', 'copy_paste_mode=flip', 'auto_augment=randaugment', 'erasing=0.4', 'cfg=None', 'tracker=botsort.yaml', 'data=./data.yaml', 'save_dir=C:\\Users\\user\\Documents\\DARLYN\\pubmat-checker\\runs\\detect\\train']' returned non-zero exit status 1.
WARNING No valid fitness values to plot (all iterations may have failed)

Tuner: 1/50 iterations complete  (88.30s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune
Tuner: Best fitness=0.0 observed at iteration 1
Tuner: Best fitness metrics are {'fitness': 0.0}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune\weights
Printing 'C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 2/50 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.92244, 'weight_decay': 0.0, 'warmup_epochs': 2.99634, 'warmup_momentum': 0.79799, 'box': 7.50602, 'cls': 0.51198, 'cls_pw': 0.0, 'dfl': 1.50847, 'hsv_h': 0.01221, 'hsv_s': 0.6994, 'hsv_v': 0.32128, 'degrees': 0.0, 'translate': 0.09842, 'scale': 0.39588, 'shear': 0.0, 'perspective': 0.001, 'flipud': 0.01536, 'fliplr': 0.50331, 'bgr': 0.00408, 'mosaic': 0.92509, 'mixup': 0.0, 'cutmix': 0.00217, 'copy_paste': 0.0, 'close_mosaic': 10}
ERROR training failure for hyperparameter tuning iteration 2
Command '['c:\\python313\\python.exe', '-m', 'ultralytics.cfg.__init__', 'train', 'task=detect', 'mode=train', 'model=yolov8n.pt', 'epochs=30', 'time=None', 'patience=10', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=None', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=True', 'optimizer=AdamW', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=10', 'resume=False', 'amp=True', 'fraction=1.0', 'profile=False', 'freeze=None', 'multi_scale=0.0', 'compile=False', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'end2end=None', 'source=None', 'vid_stride=1', 'stream_buffer=False', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'embed=None', 'show=False', 'save_frames=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'show_boxes=True', 'line_width=None', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=True', 'opset=None', 'workspace=None', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.92244', 'weight_decay=0.0', 'warmup_epochs=2.99634', 'warmup_momentum=0.79799', 'warmup_bias_lr=0.1', 'box=7.50602', 'cls=0.51198', 'cls_pw=0.0', 'dfl=1.50847', 'pose=12.0', 'kobj=1.0', 'rle=1.0', 'angle=1.0', 'nbs=64', 'hsv_h=0.01221', 'hsv_s=0.6994', 'hsv_v=0.32128', 'degrees=0.0', 'translate=0.09842', 'scale=0.39588', 'shear=0.0', 'perspective=0.001', 'flipud=0.01536', 'fliplr=0.50331', 'bgr=0.00408', 'mosaic=0.92509', 'mixup=0.0', 'cutmix=0.00217', 'copy_paste=0.0', 'copy_paste_mode=flip', 'auto_augment=randaugment', 'erasing=0.4', 'cfg=None', 'tracker=botsort.yaml', 'data=./data.yaml', 'save_dir=C:\\Users\\user\\Documents\\DARLYN\\pubmat-checker\\runs\\detect\\train2']' returned non-zero exit status 1.
WARNING No valid fitness values to plot (all iterations may have failed)

Tuner: 2/50 iterations complete  (164.27s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune
Tuner: Best fitness=0.0 observed at iteration 1
Tuner: Best fitness metrics are {'fitness': 0.0}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune\weights
Printing 'C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 3/50 with hyperparameters: {'lr0': 0.00031, 'lrf': 0.01582, 'momentum': 0.93193, 'weight_decay': 0.0, 'warmup_epochs': 2.99663, 'warmup_momentum': 0.79696, 'box': 7.50677, 'cls': 0.49185, 'cls_pw': 0.00601, 'dfl': 1.50236, 'hsv_h': 0.01667, 'hsv_s': 0.87448, 'hsv_v': 0.39495, 'degrees': 0.00337, 'translate': 0.09926, 'scale': 0.49821, 'shear': 0.0025, 'perspective': 0.0, 'flipud': 0.00211, 'fliplr': 0.45324, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.0, 'cutmix': 0.00778, 'copy_paste': 1e-05, 'close_mosaic': 10}
ERROR training failure for hyperparameter tuning iteration 3
Command '['c:\\python313\\python.exe', '-m', 'ultralytics.cfg.__init__', 'train', 'task=detect', 'mode=train', 'model=yolov8n.pt', 'epochs=30', 'time=None', 'patience=10', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=None', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=True', 'optimizer=AdamW', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=10', 'resume=False', 'amp=True', 'fraction=1.0', 'profile=False', 'freeze=None', 'multi_scale=0.0', 'compile=False', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'end2end=None', 'source=None', 'vid_stride=1', 'stream_buffer=False', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'embed=None', 'show=False', 'save_frames=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'show_boxes=True', 'line_width=None', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=True', 'opset=None', 'workspace=None', 'nms=False', 'lr0=0.00031', 'lrf=0.01582', 'momentum=0.93193', 'weight_decay=0.0', 'warmup_epochs=2.99663', 'warmup_momentum=0.79696', 'warmup_bias_lr=0.1', 'box=7.50677', 'cls=0.49185', 'cls_pw=0.00601', 'dfl=1.50236', 'pose=12.0', 'kobj=1.0', 'rle=1.0', 'angle=1.0', 'nbs=64', 'hsv_h=0.01667', 'hsv_s=0.87448', 'hsv_v=0.39495', 'degrees=0.00337', 'translate=0.09926', 'scale=0.49821', 'shear=0.0025', 'perspective=0.0', 'flipud=0.00211', 'fliplr=0.45324', 'bgr=0.0', 'mosaic=1.0', 'mixup=0.0', 'cutmix=0.00778', 'copy_paste=1e-05', 'copy_paste_mode=flip', 'auto_augment=randaugment', 'erasing=0.4', 'cfg=None', 'tracker=botsort.yaml', 'data=./data.yaml', 'save_dir=C:\\Users\\user\\Documents\\DARLYN\\pubmat-checker\\runs\\detect\\train2']' returned non-zero exit status 1.
WARNING No valid fitness values to plot (all iterations may have failed)

Tuner: 3/50 iterations complete  (250.23s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune
Tuner: Best fitness=0.0 observed at iteration 1
Tuner: Best fitness metrics are {'fitness': 0.0}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune\weights
Printing 'C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 4/50 with hyperparameters: {'lr0': 1e-05, 'lrf': 0.01316, 'momentum': 0.93606, 'weight_decay': 0.0, 'warmup_epochs': 3.88045, 'warmup_momentum': 0.79058, 'box': 7.50039, 'cls': 0.51168, 'cls_pw': 0.0, 'dfl': 1.5086, 'hsv_h': 0.01651, 'hsv_s': 0.87259, 'hsv_v': 0.38988, 'degrees': 0.00174, 'translate': 0.11529, 'scale': 0.65833, 'shear': 0.00017, 'perspective': 0.0, 'flipud': 0.00592, 'fliplr': 0.45478, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.0, 'cutmix': 0.00878, 'copy_paste': 0.0, 'close_mosaic': 10}
ERROR training failure for hyperparameter tuning iteration 4
Command '['c:\\python313\\python.exe', '-m', 'ultralytics.cfg.__init__', 'train', 'task=detect', 'mode=train', 'model=yolov8n.pt', 'epochs=30', 'time=None', 'patience=10', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=None', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=True', 'optimizer=AdamW', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=10', 'resume=False', 'amp=True', 'fraction=1.0', 'profile=False', 'freeze=None', 'multi_scale=0.0', 'compile=False', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'end2end=None', 'source=None', 'vid_stride=1', 'stream_buffer=False', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'embed=None', 'show=False', 'save_frames=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'show_boxes=True', 'line_width=None', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=True', 'opset=None', 'workspace=None', 'nms=False', 'lr0=1e-05', 'lrf=0.01316', 'momentum=0.93606', 'weight_decay=0.0', 'warmup_epochs=3.88045', 'warmup_momentum=0.79058', 'warmup_bias_lr=0.1', 'box=7.50039', 'cls=0.51168', 'cls_pw=0.0', 'dfl=1.5086', 'pose=12.0', 'kobj=1.0', 'rle=1.0', 'angle=1.0', 'nbs=64', 'hsv_h=0.01651', 'hsv_s=0.87259', 'hsv_v=0.38988', 'degrees=0.00174', 'translate=0.11529', 'scale=0.65833', 'shear=0.00017', 'perspective=0.0', 'flipud=0.00592', 'fliplr=0.45478', 'bgr=0.0', 'mosaic=1.0', 'mixup=0.0', 'cutmix=0.00878', 'copy_paste=0.0', 'copy_paste_mode=flip', 'auto_augment=randaugment', 'erasing=0.4', 'cfg=None', 'tracker=botsort.yaml', 'data=./data.yaml', 'save_dir=C:\\Users\\user\\Documents\\DARLYN\\pubmat-checker\\runs\\detect\\train2']' returned non-zero exit status 1.
WARNING No valid fitness values to plot (all iterations may have failed)

Tuner: 4/50 iterations complete  (333.66s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune
Tuner: Best fitness=0.0 observed at iteration 1
Tuner: Best fitness metrics are {'fitness': 0.0}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune\weights
Printing 'C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 5/50 with hyperparameters: {'lr0': 0.00205, 'lrf': 0.01, 'momentum': 0.98, 'weight_decay': 0.0, 'warmup_epochs': 2.46064, 'warmup_momentum': 0.65104, 'box': 7.50673, 'cls': 0.50079, 'cls_pw': 0.0055, 'dfl': 1.60675, 'hsv_h': 0.01796, 'hsv_s': 0.83837, 'hsv_v': 0.39984, 'degrees': 0.0, 'translate': 0.09928, 'scale': 0.49867, 'shear': 0.002, 'perspective': 0.001, 'flipud': 0.00179, 'fliplr': 0.60278, 'bgr': 0.0, 'mosaic': 0.99934, 'mixup': 0.0, 'cutmix': 0.00103, 'copy_paste': 1e-05, 'close_mosaic': 8}
ERROR training failure for hyperparameter tuning iteration 5
Command '['c:\\python313\\python.exe', '-m', 'ultralytics.cfg.__init__', 'train', 'task=detect', 'mode=train', 'model=yolov8n.pt', 'epochs=30', 'time=None', 'patience=10', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=None', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=True', 'optimizer=AdamW', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=8', 'resume=False', 'amp=True', 'fraction=1.0', 'profile=False', 'freeze=None', 'multi_scale=0.0', 'compile=False', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'end2end=None', 'source=None', 'vid_stride=1', 'stream_buffer=False', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'embed=None', 'show=False', 'save_frames=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'show_boxes=True', 'line_width=None', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=True', 'opset=None', 'workspace=None', 'nms=False', 'lr0=0.00205', 'lrf=0.01', 'momentum=0.98', 'weight_decay=0.0', 'warmup_epochs=2.46064', 'warmup_momentum=0.65104', 'warmup_bias_lr=0.1', 'box=7.50673', 'cls=0.50079', 'cls_pw=0.0055', 'dfl=1.60675', 'pose=12.0', 'kobj=1.0', 'rle=1.0', 'angle=1.0', 'nbs=64', 'hsv_h=0.01796', 'hsv_s=0.83837', 'hsv_v=0.39984', 'degrees=0.0', 'translate=0.09928', 'scale=0.49867', 'shear=0.002', 'perspective=0.001', 'flipud=0.00179', 'fliplr=0.60278', 'bgr=0.0', 'mosaic=0.99934', 'mixup=0.0', 'cutmix=0.00103', 'copy_paste=1e-05', 'copy_paste_mode=flip', 'auto_augment=randaugment', 'erasing=0.4', 'cfg=None', 'tracker=botsort.yaml', 'data=./data.yaml', 'save_dir=C:\\Users\\user\\Documents\\DARLYN\\pubmat-checker\\runs\\detect\\train2']' returned non-zero exit status 1.
WARNING No valid fitness values to plot (all iterations may have failed)

Tuner: 5/50 iterations complete  (416.23s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune
Tuner: Best fitness=0.0 observed at iteration 1
Tuner: Best fitness metrics are {'fitness': 0.0}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune\weights
Printing 'C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tune\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 6/50 with hyperparameters: {'lr0': 0.00904, 'lrf': 0.01, 'momentum': 0.92634, 'weight_decay': 0.001, 'warmup_epochs': 2.69654, 'warmup_momentum': 0.6265, 'box': 7.50657, 'cls': 0.5105, 'cls_pw': 0.00436, 'dfl': 1.25488, 'hsv_h': 0.01704, 'hsv_s': 0.72201, 'hsv_v': 0.29556, 'degrees': 0.0029, 'translate': 0.13234, 'scale': 0.51112, 'shear': 0.00221, 'perspective': 0.00058, 'flipud': 0.00632, 'fliplr': 0.35259, 'bgr': 0.00393, 'mosaic': 0.6723, 'mixup': 0.0, 'cutmix': 0.01026, 'copy_paste': 1e-05, 'close_mosaic': 8}
ERROR training failure for hyperparameter tuning iteration 6
Command '['c:\\python313\\python.exe', '-m', 'ultralytics.cfg.__init__', 'train', 'task=detect', 'mode=train', 'model=yolov8n.pt', 'epochs=30', 'time=None', 'patience=10', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=None', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=True', 'optimizer=AdamW', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=8', 'resume=False', 'amp=True', 'fraction=1.0', 'profile=False', 'freeze=None', 'multi_scale=0.0', 'compile=False', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'end2end=None', 'source=None', 'vid_stride=1', 'stream_buffer=False', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'embed=None', 'show=False', 'save_frames=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'show_boxes=True', 'line_width=None', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=True', 'opset=None', 'workspace=None', 'nms=False', 'lr0=0.00904', 'lrf=0.01', 'momentum=0.92634', 'weight_decay=0.001', 'warmup_epochs=2.69654', 'warmup_momentum=0.6265', 'warmup_bias_lr=0.1', 'box=7.50657', 'cls=0.5105', 'cls_pw=0.00436', 'dfl=1.25488', 'pose=12.0', 'kobj=1.0', 'rle=1.0', 'angle=1.0', 'nbs=64', 'hsv_h=0.01704', 'hsv_s=0.72201', 'hsv_v=0.29556', 'degrees=0.0029', 'translate=0.13234', 'scale=0.51112', 'shear=0.00221', 'perspective=0.00058', 'flipud=0.00632', 'fliplr=0.35259', 'bgr=0.00393', 'mosaic=0.6723', 'mixup=0.0', 'cutmix=0.01026', 'copy_paste=1e-05', 'copy_paste_mode=flip', 'auto_augment=randaugment', 'erasing=0.4', 'cfg=None', 'tracker=botsort.yaml', 'data=./data.yaml', 'save_dir=C:\\Users\\user\\Documents\\DARLYN\\pubmat-checker\\runs\\detect\\train2']' returned non-zero exit status 1.

### Tuned Model (Best Params)

In [17]:
# Re-initialize before full tuned training run
model = YOLO("yolov8s.pt")

model.train(
    data="./data.yaml",
    name="tuned_model",
    epochs=150,
    patience=20,
    device=0,
    workers=4,
    imgsz=640,
    batch=16,
    seed=42,              # fixed seed for reproducibility

    # Best hyperparameters from tuning

    lr0=0.01,
    lrf=0.01,
    momentum=0.937,
    weight_decay=0.0005,
    warmup_epochs=3.0,
    warmup_momentum=0.8,
    box=7.5,
    cls=0.5,
    cls_pw=0.0,
    dfl=1.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=0.0,
    translate=0.1,
    scale=0.5,
    shear=0.0,
    perspective=0.0,
    flipud=0.0,
    fliplr=0.0,           # overridden: logos are orientation-sensitive
    bgr=0.0,
    mosaic=1.0,
    mixup=0.0,
    cutmix=0.0,
    copy_paste=0.0,
    close_mosaic=10
)

New https://pypi.org/project/ultralytics/8.4.41 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=./data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=150, erasing=0.4, exist_ok=False, fliplr=0.0, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=tuned_model, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tuned_model, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=8

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119144  ultralytics.nn.modules.head.Detect           [8, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,138,696 parameters, 11,138,680 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 1091.3795.4 MB/s, size: 216.9 KB)
train: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\train.cache... 1445 images, 139 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1445/1445 116.6Mit/s 0.0s
val: Fast image access  (ping: 0.10.1 ms, read: 266.977.0 MB/s, size: 222.3 KB)
val: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 127.4Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000833, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tuned_model\labels.jpg...
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tuned_model
Starting training for 150 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/150      3.73G      1.084      2.311      1.105         28        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.5s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.681      0.826      0.809       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/150      3.44G     0.7265      1.029     0.9584         17        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.6s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.806      0.875      0.901      0.745

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/150      3.42G       0.69      0.846     0.9368         24        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.868       0.88      0.915      0.766

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/150      3.42G     0.6273      0.761     0.9171         24        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.888      0.875      0.929      0.794

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/150      3.42G      0.591     0.6739     0.9038         21        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.882      0.918      0.947      0.814

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/150      3.46G     0.5593     0.6286     0.8894         27        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.909       0.92      0.956      0.834

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/150      3.41G     0.5234     0.5579     0.8773          7        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.9s0.3s
                   all        334        992      0.935      0.928      0.965       0.86

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/150      3.42G     0.5229     0.5423     0.8787         12        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.5s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.7s0.3s
                   all        334        992      0.919      0.926      0.954      0.837

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/150      3.42G     0.4866     0.5192     0.8671         37        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.6s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.954      0.939      0.967      0.874

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/150      3.43G     0.4855     0.5128      0.866         23        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.7s0.3s
                   all        334        992      0.919      0.934      0.958       0.87

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/150      3.41G     0.4678     0.4932     0.8554         28        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.933      0.932      0.958      0.867

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/150      3.37G     0.4475       0.46     0.8523         18        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.946       0.95      0.976      0.886

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/150      3.37G     0.4572     0.4624     0.8526         14        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 31.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.954      0.936      0.972      0.889

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/150      3.42G     0.4311     0.4444     0.8452         34        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.935      0.946      0.973      0.893

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/150      3.41G     0.4288     0.4565     0.8423         31        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.5s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.939      0.933      0.972      0.891

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/150      3.42G     0.4221     0.4337     0.8419         34        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.943      0.944      0.969      0.886

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/150      3.37G     0.4058     0.4251      0.833         33        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.951      0.931      0.967      0.893

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/150      3.44G     0.4016     0.4025     0.8363         14        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992       0.95      0.944      0.971      0.899

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/150       3.4G     0.3917     0.3896      0.832         24        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.951      0.949      0.979      0.916

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/150      3.45G     0.3821      0.394     0.8323         15        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.956      0.959      0.974      0.912

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/150      3.43G     0.3824     0.3845     0.8327         18        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.946      0.944      0.956      0.894

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/150      3.43G      0.386     0.3805     0.8291         27        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.6s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.933      0.955      0.975      0.907

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/150      3.43G     0.3805     0.3813     0.8287         19        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.7s0.3s
                   all        334        992      0.945      0.965      0.979       0.92

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/150      3.42G     0.3671      0.381     0.8261         21        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992       0.95       0.95      0.978      0.919

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/150      3.42G     0.3636     0.3625     0.8226         39        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.952       0.95      0.978       0.92

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/150      3.46G      0.362     0.3687     0.8215         26        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.943      0.962      0.976      0.921

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/150      3.41G     0.3557      0.375      0.826         30        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.959      0.969       0.98      0.923

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/150      3.42G     0.3581     0.3691     0.8216         19        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.946      0.955      0.978      0.927

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/150      3.43G     0.3451     0.3477     0.8203         30        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.6s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992       0.96      0.951       0.98      0.926

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/150      3.44G     0.3357     0.3335       0.82         32        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.967      0.954      0.981      0.932

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/150      3.43G     0.3319     0.3338     0.8158         11        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.7s0.3s
                   all        334        992      0.969      0.957      0.981      0.931

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/150      3.43G     0.3366     0.3301     0.8166         19        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.957      0.967      0.983      0.936

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/150      3.44G     0.3303     0.3223      0.815         19        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.963      0.962      0.984      0.933

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/150      3.44G     0.3238     0.3212     0.8152         18        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.961      0.949       0.98      0.929

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6, 7])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x00000237EE246820>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,     0.97403,     0.97403,           0],
       [          1,           1,           1, ...,     0.99107,     0.99107,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       ...,
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,     0.97351,     0.97351,           0],
       [          1,           1,           1, ...,     0.85437,     0.85437,           0]], shape=(8, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

In [18]:
tuned_model = YOLO("runs/detect/tuned_model/weights/best.pt")

### Tuned Model (Longer Training)

In [19]:
# Re-initialize before extended training run
model = YOLO("yolov8s.pt")

# NOTE: imgsz=800 increases memory and compute per batch significantly.
# If you experience OOM errors, reduce batch size or revert to imgsz=640.
model.train(
    data="./data.yaml",
    name="tuned_model_v2",
    epochs=300,
    patience=30,
    device=0,
    workers=4,
    imgsz=800,
    batch=8,              
    seed=42,              

    # Best hyperparameters from tuning
    lr0=0.01,
    lrf=0.01,
    momentum=0.937,
    weight_decay=0.0005,
    warmup_epochs=3.0,
    warmup_momentum=0.8,
    box=7.5,
    cls=0.5,
    cls_pw=0.0,
    dfl=1.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=0.0,
    translate=0.1,
    scale=0.5,
    shear=0.0,
    perspective=0.0,
    flipud=0.0,
    fliplr=0.0,           
    bgr=0.0,
    mosaic=1.0,
    mixup=0.0,
    cutmix=0.0,
    copy_paste=0.0,
    close_mosaic=10
)

New https://pypi.org/project/ultralytics/8.4.41 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=./data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=300, erasing=0.4, exist_ok=False, fliplr=0.0, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=800, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=tuned_model_v2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=30, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tuned_model_v2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=8

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119144  ultralytics.nn.modules.head.Detect           [8, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,138,696 parameters, 11,138,680 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.00.0 ms, read: 1926.0607.8 MB/s, size: 216.9 KB)
train: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\train.cache... 1445 images, 139 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1445/1445 606.1Mit/s 0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 261.969.9 MB/s, size: 222.3 KB)
val: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 87.6Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000833, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tuned_model_v2\labels.jpg...
Image sizes 800 train, 800 val
Using 4 dataloader workers
Logging results to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\tuned_model_v2
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/300       2.9G     0.9753      2.225      1.089         17        800: 100% ━━━━━━━━━━━━ 181/181 3.5it/s 51.6s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.0it/s 4.2s0.2s
                   all        334        992      0.752      0.862      0.881      0.722

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/300      2.74G     0.6987     0.9634     0.9617         15        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.3s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.817      0.841      0.878      0.738

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/300      2.71G     0.6371     0.7842     0.9206         33        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.892      0.889      0.952      0.815

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/300      2.72G      0.607      0.718     0.9164         27        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.3it/s 4.0s0.2s
                   all        334        992       0.88      0.886      0.944      0.814

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/300      2.71G     0.5715     0.6487        0.9         36        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 48.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 4.7it/s 4.5s0.2s
                   all        334        992      0.905      0.894      0.944      0.833

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/300      2.71G     0.5239     0.5758     0.8924         24        800: 100% ━━━━━━━━━━━━ 181/181 3.6it/s 50.4s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.3it/s 3.9s0.2s
                   all        334        992      0.899      0.917       0.96      0.861

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/300      2.78G     0.5059     0.5686     0.8915         22        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992      0.911      0.918      0.955       0.85

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/300      2.73G     0.5054     0.5344     0.8878         20        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.937      0.934      0.959      0.864

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/300      2.71G     0.4597      0.477      0.872         26        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 48.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.1it/s 4.1s0.2s
                   all        334        992      0.944      0.938      0.966      0.883

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/300      2.71G     0.4668     0.4834     0.8739         27        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.3s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.915      0.938      0.953      0.869

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/300      2.71G     0.4539     0.4818     0.8718         22        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 48.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.2it/s 4.0s0.2s
                   all        334        992      0.914      0.941      0.941      0.857

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/300       2.7G     0.4363      0.489     0.8632         31        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.929      0.918      0.955      0.881

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/300      2.83G     0.4241     0.4596     0.8588         22        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 48.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.6it/s 3.8s0.2s
                   all        334        992      0.934      0.943      0.962      0.884

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/300      2.83G      0.411     0.4286     0.8535         31        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.3s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.959       0.94      0.975      0.906

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/300      2.71G     0.4107     0.4397     0.8537         29        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 48.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.6it/s 3.8s0.2s
                   all        334        992      0.955      0.953      0.977      0.902

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/300      2.82G     0.4005      0.417     0.8496         28        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992      0.953      0.967      0.974      0.913

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/300      2.72G     0.3994     0.3942     0.8468         33        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.6it/s 3.8s0.2s
                   all        334        992      0.956      0.947      0.974      0.904

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/300       2.8G     0.3851     0.3936     0.8407         15        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.937      0.946      0.973      0.909

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/300      2.71G     0.3722     0.3652     0.8425         29        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.3s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992      0.951      0.955      0.976      0.914

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/300       2.7G     0.3728     0.3944     0.8409         15        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.4s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992      0.943      0.937      0.972       0.91

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/300      2.82G     0.3708     0.3875     0.8411         29        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.6it/s 3.8s0.2s
                   all        334        992      0.952      0.949      0.975       0.92

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/300      2.71G     0.3736       0.39     0.8402         22        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 48.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.952      0.953      0.976      0.913

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/300       2.8G     0.3602     0.3696     0.8374         17        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992      0.951      0.952      0.978      0.918

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/300      2.83G     0.3596     0.3612     0.8377         20        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.949      0.943      0.974      0.912

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/300       2.8G     0.3702     0.3627     0.8385         23        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.967      0.951      0.978      0.923

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/300      2.82G     0.3444     0.3703     0.8369         24        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 48.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992      0.955      0.954      0.976      0.921

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/300      2.71G     0.3417     0.3455     0.8345         25        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992      0.962      0.951      0.978      0.927

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/300       2.7G     0.3371     0.3375     0.8315         21        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 48.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.963      0.952      0.977      0.926

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/300      2.71G     0.3389      0.338     0.8329         26        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992      0.964      0.953      0.981      0.927

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/300       2.8G     0.3344     0.3468     0.8271         30        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.4it/s 3.9s0.2s
                   all        334        992      0.953      0.951      0.978      0.925

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/300      2.82G     0.3295     0.3417     0.8288         30        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992      0.966      0.961      0.984      0.935

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/300       2.8G     0.3221     0.3206     0.8252         23        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 48.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992       0.97      0.971      0.983      0.938

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/300      2.71G     0.3354     0.3338     0.8327         27        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992      0.963      0.958       0.98      0.933

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/300       2.7G     0.3116     0.3084      0.828         18        800: 100% ━━━━━━━━━━━━ 181/181 3.7it/s 49.3s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.5it/s 3.8s0.2s
                   all        334        992      0.964      0.951      0.982      0.935


ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6, 7])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x00000236D08EE820>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,     0.95541,     0.95541,           0],
       [          1,           1,           1, ...,      0.9823,      0.9823,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       ...,
       [          1,           1,           1, ...,     0.62143,     0.62143,           0],
       [          1,           1,           1, ...,        0.98,        0.98,           0],
       [          1,           1,           1, ...,     0.51765,     0.51765,           0]], shape=(8, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

In [20]:
tuned_model_v2 = YOLO("runs/detect/tuned_model_v2/weights/best.pt")

## Metrics

In [60]:
def get_metrics(model, ver, split):
    metrics = model.val(
        data="./data.yaml",
        plots=True,
        save=True,
        save_json=True,
        project="./results",
        name=f"{ver}_{split}",
        split=split,
        verbose=False
    )

    metrics_df = pd.DataFrame({
        "mAP50": [metrics.box.map50],
        "mAP50-95": [metrics.box.map],
        "Precision": [metrics.box.mp],
        "Recall": [metrics.box.mr]
    })

    # Per-class metrics from class_result()
    rows = []
    for i, class_name in metrics.names.items():
        p, r, ap50, ap = metrics.box.class_result(i)
        rows.append({
            "Class": class_name,
            "Precision": p,
            "Recall": r,
            "mAP50": ap50,
            "mAP50-95": ap
        })

    per_class_df = pd.DataFrame(rows)

    return metrics_df, per_class_df

### Evaluate All Models (Test Set)

In [ ]:


base_metrics_df, base_per_class_df = get_metrics(base_model, "base_model", "test")
tuned_metrics_df, tuned_per_class_df = get_metrics(tuned_model, "tuned_model", "test")
tuned_metrics_df_v2, tuned_per_class_df_v2 = get_metrics(tuned_model_v2, "tuned_model_v2", "test")

Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 954.6621.9 MB/s, size: 225.6 KB)
val: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\test.cache... 320 images, 30 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 320/320 111.8Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 20/20 5.2it/s 3.8s0.1s
                   all        320        923      0.948       0.97      0.984      0.945
Speed: 1.8ms preprocess, 4.4ms inference, 0.0ms loss, 1.6ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\base_model_test4\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\base_model_test4
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 890.7139.6 MB/s, size: 175.1 KB)
val: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\test.cache... 320 images, 30 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 320/320 111.8Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 20/20 4.2it/s 4.7s0.2s
                   all        320        923      0.966      0.977      0.989       0.97
Speed: 1.2ms preprocess, 8.5ms inference, 0.0ms loss, 1.1ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\tuned_model_test3\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\tuned_model_test3
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.00.0 ms, read: 1801.1554.7 MB/s, size: 234.0 KB)
val: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\test.cache... 320 images, 30 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 320/320 149.1Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 20/20 3.1it/s 6.5s0.3s
                   all        320        923      0.973      0.976      0.987      0.965
Speed: 2.5ms preprocess, 12.9ms inference, 0.0ms loss, 0.8ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\tuned_model_v2_test3\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\tuned_model_v2_test3

In [55]:
print("Metrics for Models on Test Set:")
summarized_metrics = pd.concat([base_metrics_df, tuned_metrics_df, tuned_metrics_df_v2])
summarized_metrics.index = ["Base Model", "Tuned Model", "Tuned Model v2"]
summarized_metrics

Metrics for Models on Test Set:

                   mAP50  mAP50-95  Precision    Recall
Base Model      0.984409  0.945058   0.947933  0.970331
Tuned Model     0.989044  0.970067   0.966370  0.977421
Tuned Model v2  0.986810  0.964807   0.973215  0.975659

In [57]:
print("\nPer-class Metrics for Tuned Model on Test Set:")
tuned_per_class_df

Per-class Metrics for Tuned Model on Test Set:

            Class  Precision    Recall     mAP50  mAP50-95
0     NYC_Correct   0.964625  0.992481  0.991414  0.990365
1   NYC_Incorrect   0.991020  0.985416  0.987411  0.975644
2      BP_Correct   0.919753  1.000000  0.974765  0.974543
3    BP_Incorrect   0.980661  0.946565  0.989605  0.970449
4      SK_Correct   0.943366  1.000000  0.991361  0.991361
5    SK_Incorrect   1.000000  0.951050  0.993432  0.936912
6    YORP_Correct   0.955386  0.991935  0.994437  0.993250
7  YORP_Incorrect   0.976152  0.951919  0.989925  0.928011

In [58]:
print("\nPer-class Metrics for Tuned Model v2 on Test Set:")
tuned_per_class_df_v2

Per-class Metrics for Tuned Model v2 on Test Set:

            Class  Precision    Recall     mAP50  mAP50-95
0     NYC_Correct   0.970627  0.993826  0.992649  0.991533
1   NYC_Incorrect   0.980961  0.973214  0.993566  0.980989
2      BP_Correct   0.937299  1.000000  0.979384  0.978017
3    BP_Incorrect   0.992036  0.950874  0.990582  0.972974
4      SK_Correct   0.959186  1.000000  0.985945  0.980466
5    SK_Incorrect   0.988083  0.968750  0.979479  0.905814
6    YORP_Correct   0.958845  1.000000  0.985789  0.983698
7  YORP_Incorrect   0.998683  0.918605  0.987087  0.924963

### Evaluate All Models (Val Set)

In [62]:

base_metrics_val_df, base_per_class_df = get_metrics(base_model, "base_model", "val")
tuned_metrics_val_df, tuned_per_class_df = get_metrics(tuned_model, "tuned_model", "val")
tuned_metrics_val_df_v2, tuned_per_class_df_v2 = get_metrics(tuned_model_v2, "tuned_model_v2", "val")

Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1420.7284.7 MB/s, size: 262.5 KB)
val: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 127.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 4.7it/s 4.5s0.2s
                   all        334        992      0.956      0.969      0.984       0.94
Speed: 1.5ms preprocess, 4.9ms inference, 0.0ms loss, 1.9ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\base_model_val4\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\base_model_val4
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.00.0 ms, read: 1993.6628.4 MB/s, size: 282.4 KB)
val: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 107.8Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 4.5it/s 4.6s0.2s
                   all        334        992      0.978       0.98      0.988      0.964
Speed: 0.9ms preprocess, 8.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\tuned_model_val2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\tuned_model_val2
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1694.5516.9 MB/s, size: 530.5 KB)
val: Scanning C:\Users\user\Documents\DARLYN\pubmat-checker\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 127.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.8it/s 7.4s0.4s
                   all        334        992      0.979      0.978      0.989      0.965
Speed: 4.4ms preprocess, 13.1ms inference, 0.0ms loss, 0.8ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\tuned_model_v2_val2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\pubmat-checker\runs\detect\results\tuned_model_v2_val2

In [63]:
print("Metrics for Models on Validation Set:")
summarized_metrics_val = pd.concat([base_metrics_val_df, tuned_metrics_val_df, tuned_metrics_val_df_v2])
summarized_metrics_val.index = ["Base Model", "Tuned Model", "Tuned Model v2"]
summarized_metrics_val

Metrics for Models on Validation Set:

                   mAP50  mAP50-95  Precision    Recall
Base Model      0.984379  0.939770   0.956346  0.968665
Tuned Model     0.988317  0.964467   0.978304  0.979841
Tuned Model v2  0.989134  0.965483   0.978935  0.977560

In [65]:
print("Per-class Metrics for Tuned Model on Validation Set:")
tuned_per_class_df

Per-class Metrics for Tuned Model on Validation Set:

            Class  Precision    Recall     mAP50  mAP50-95
0     NYC_Correct   0.976818  0.993333  0.993733  0.989527
1   NYC_Incorrect   0.999560  0.990991  0.995000  0.978379
2      BP_Correct   0.947573  0.988438  0.987361  0.981084
3    BP_Incorrect   0.988623  0.964539  0.993202  0.967151
4      SK_Correct   0.959550  0.992857  0.987201  0.982160
5    SK_Incorrect   0.996087  0.954023  0.962706  0.914109
6    YORP_Correct   0.961621  1.000000  0.994597  0.991537
7  YORP_Incorrect   0.996598  0.954545  0.992736  0.911792

In [66]:
print("Per-class Metrics for Tuned Model v2 on Validation Set:")
tuned_per_class_df_v2

Per-class Metrics for Tuned Model v2 on Validation Set:

            Class  Precision    Recall     mAP50  mAP50-95
0     NYC_Correct   0.976785  0.993333  0.993855  0.990550
1   NYC_Incorrect   0.996608  0.981982  0.994910  0.981640
2      BP_Correct   0.954335  0.979645  0.983378  0.975183
3    BP_Incorrect   0.984588  0.971631  0.987762  0.967351
4      SK_Correct   0.978950  0.996549  0.992009  0.983672
5    SK_Incorrect   0.983132  0.965517  0.988028  0.927577
6    YORP_Correct   0.957787  1.000000  0.990255  0.988275
7  YORP_Incorrect   0.999296  0.931818  0.982877  0.909614

### Model Comparison Summary

In [70]:
train_df = summarized_metrics.copy()
train_df["Split"] = "Test"

val_df = summarized_metrics_val.copy()
val_df["Split"] = "Val"

combined = pd.concat([train_df, val_df]).reset_index().rename(columns={"index": "Model"})
combined = combined.set_index(["Model", "Split"]).round(4)

combined

                       mAP50  mAP50-95  Precision  Recall
Model          Split
Base Model     Test   0.9844    0.9451     0.9479  0.9703
Tuned Model    Test   0.9890    0.9701     0.9664  0.9774
Tuned Model v2 Test   0.9868    0.9648     0.9732  0.9757
Base Model     Val    0.9844    0.9398     0.9563  0.9687
Tuned Model    Val    0.9883    0.9645     0.9783  0.9798
Tuned Model v2 Val    0.9891    0.9655     0.9789  0.9776