# Logo Detection — YOLO Model Training & Comparison

This notebook trains and compares multiple YOLO model variants for logo detection.
The task is to detect 4 logo types (NYC, BP, SK, YORP), each labeled as either **Correct** or **Incorrect** placement — 8 classes total.

**Pipeline overview:**
1. Setup & dependencies
2. Dataset configuration and integrity checks
3. Baseline model (YOLOv8n — fast, low-memory sanity check)
4. Hyperparameter tuning (on YOLOv8s)
5. Tuned model training across multiple YOLO architectures for comparison
6. Evaluation and model comparison

## 1. Setup

In [ ]:
# !pip install ultralytics -q

In [2]:
import pandas as pd
import torch
from ultralytics import YOLO
import os
import yaml
from collections import Counter

print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

CUDA available: True
GPU: NVIDIA GeForce RTX 3050

In [ ]:
# Uncomment if running on Google Colab
# from google.colab import drive
# drive.mount('/content/drive')
# path = "/content/drive/MyDrive/pubmat-checker"

## 2. Dataset Configuration

We define 8 classes (4 logo brands × 2 correctness states) and write a `data.yaml` file
that YOLO uses to locate images and labels during training.

Expected directory layout:
```
data/
  images/
    train/  val/  test/
  labels/
    train/  val/  test/
```

In [3]:
data = {
    "path": "./data",
    "train": "images/train",
    "val": "images/val",
    "test": "images/test",
    "names": {
        0: "NYC_Correct",
        1: "NYC_Incorrect",
        2: "BP_Correct",
        3: "BP_Incorrect",
        4: "SK_Correct",
        5: "SK_Incorrect",
        6: "YORP_Correct",
        7: "YORP_Incorrect",
    }
}

with open("./data.yaml", "w") as f:
    yaml.dump(data, f)

print("data.yaml created.")

data.yaml created.

### 2.1 Data Integrity Check

Before training, we verify:
- Every image has a corresponding label file (and vice versa)
- Class distribution is visible across all splits

In [4]:
def check_split(base_path, class_names, split):
    """Check image/label integrity and print class distribution for a given split."""
    image_dir = os.path.join(base_path, "images", split)
    label_dir = os.path.join(base_path, "labels", split)

    image_stems = {
        os.path.splitext(f)[0]
        for f in os.listdir(image_dir)
        if f.lower().endswith((".png", ".jpg", ".jpeg", ".bmp"))
    }
    label_stems = {
        os.path.splitext(f)[0]
        for f in os.listdir(label_dir)
        if f.lower().endswith(".txt")
    }

    errors = []
    for stem in image_stems - label_stems:
        errors.append(f"Image has no label: {stem}")
    for stem in label_stems - image_stems:
        errors.append(f"Label has no image: {stem}")

    class_counts = Counter()
    for stem in label_stems:
        with open(os.path.join(label_dir, stem + ".txt")) as f:
            for line in f:
                parts = line.strip().split()
                if parts:
                    class_counts[int(parts[0])] += 1

    total = sum(class_counts.values())
    print(f"\n--- {split.upper()} Split ---")
    print(f"Images: {len(image_stems)} | Labels: {len(label_stems)} | Annotations: {total}")
    print("\nClass Distribution:")
    rows = []
    for class_id, count in sorted(class_counts.items()):
        name = class_names.get(class_id, f"Unknown {class_id}")
        pct = (count / total) * 100 if total else 0
        print(f"  {name}: {count} ({pct:.1f}%)")
        rows.append({"Split": split, "Class": name, "Count": count, "Pct": round(pct, 1)})

    if errors:
        print("\nErrors:")
        for e in errors:
            print(" -", e)
    else:
        print("\nIntegrity check passed — no mismatches found.")

    return rows


with open("./data.yaml") as f:
    data_config = yaml.safe_load(f)

base_path = data_config["path"]
class_names = data_config["names"]
all_rows = []

for split in ["train", "val", "test"]:
    all_rows.extend(check_split(base_path, class_names, split))

--- TRAIN Split ---
Images: 1445 | Labels: 1445 | Annotations: 4195

Class Distribution:
  NYC_Correct: 596 (14.2%)
  NYC_Incorrect: 517 (12.3%)
  BP_Correct: 479 (11.4%)
  BP_Incorrect: 629 (15.0%)
  SK_Correct: 597 (14.2%)
  SK_Incorrect: 396 (9.4%)
  YORP_Correct: 609 (14.5%)
  YORP_Incorrect: 372 (8.9%)

Integrity check passed — no mismatches found.

--- VAL Split ---
Images: 334 | Labels: 334 | Annotations: 992

Class Distribution:
  NYC_Correct: 150 (15.1%)
  NYC_Incorrect: 111 (11.2%)
  BP_Correct: 128 (12.9%)
  BP_Incorrect: 141 (14.2%)
  SK_Correct: 140 (14.1%)
  SK_Incorrect: 87 (8.8%)
  YORP_Correct: 147 (14.8%)
  YORP_Incorrect: 88 (8.9%)

Integrity check passed — no mismatches found.

--- TEST Split ---
Images: 320 | Labels: 320 | Annotations: 923

Class Distribution:
  NYC_Correct: 133 (14.4%)
  NYC_Incorrect: 112 (12.1%)
  BP_Correct: 112 (12.1%)
  BP_Incorrect: 131 (14.2%)
  SK_Correct: 129 (14.0%)
  SK_Incorrect: 96 (10.4%)
  YORP_Correct: 124 (13.4%)
  YORP_Incorrect: 86 (9.3%)

Integrity check passed — no mismatches found.

## 3. Baseline Model: YOLOv8n

We start with **YOLOv8 Nano** (`yolov8n`) — the smallest variant — as a fast, low-memory baseline.
The goal here is not peak performance, but a quick sanity check that the data pipeline works
and to establish a minimum benchmark.

**Key baseline decisions:**
- `fliplr=0.0`, `flipud=0.0` — logos are orientation-sensitive; flipping would corrupt labels
- `mixup=0.0` — mixing correct/incorrect class samples would create ambiguous training signal
- `lrf=0.1` — final LR = `lr0 × lrf = 0.003 × 0.1 = 0.0003`, a gentler decay than the previous 0.01
- `cache=True` — speeds up repeated epoch reads

> **Note:** This uses `yolov8n`. The tuned models below use `yolov8s` (small) for more capacity.

In [5]:
model = YOLO("yolov8n.pt")

model.train(
    data="./data.yaml",
    name="baseline_yolov8n",
    epochs=80,
    imgsz=640,
    batch=16,
    seed=42,

    optimizer="AdamW",
    lr0=0.003,
    lrf=0.1,            
    weight_decay=0.0005,
    warmup_epochs=3.0,

    patience=20,       
    device=0,
    workers=2,
    cache=True,
    amp=True,
    val=True,

    degrees=0.0,
    translate=0.05,
    scale=0.8,
    fliplr=0.0,         
    flipud=0.0,
    mosaic=1.0,
    mixup=0.0           
)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 15.1MB/s 0.4s.4s<0.0s3s
New https://pypi.org/project/ultralytics/8.4.48 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=True, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=./data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=80, erasing=0.4, exist_ok=False, fliplr=0.0, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.003, lrf=0.1, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=baseline_yolov8n, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\baseline_yolov8n, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.8, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.05, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=8

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    752872  ultralytics.nn.modules.head.Detect           [8, 16, None, [64, 128, 256]]
Model summary: 130 layers, 3,012,408 parameters, 3,012,392 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 14.6MB/s 0.4s.3s<0.2s.1s
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 229.453.7 MB/s, size: 205.3 KB)
train: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\train... 1445 images, 139 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1445/1445 3.3Kit/s 0.4s0.1s
train: New cache created: C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\train.cache
WARNING cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
train: Caching images (1.3GB RAM): 100% ━━━━━━━━━━━━ 1445/1445 915.9it/s 1.6s0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 133.745.6 MB/s, size: 259.7 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\val... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 683.1it/s 0.5s0.0s
val: New cache created: C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\val.cache
WARNING cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.3GB RAM): 100% ━━━━━━━━━━━━ 334/334 563.8it/s 0.6s0.1s
optimizer: AdamW(lr=0.003, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\baseline_yolov8n\labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\baseline_yolov8n
Starting training for 80 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/80      1.99G      1.286      2.347      1.067         26        640: 100% ━━━━━━━━━━━━ 91/91 4.7it/s 19.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.6it/s 2.4s0.2s
                   all        334        992      0.497      0.655      0.551      0.404

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/80       2.4G      1.058        1.3     0.9832         23        640: 100% ━━━━━━━━━━━━ 91/91 5.3it/s 17.1s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.8it/s 1.9s0.2s
                   all        334        992      0.533      0.733      0.626      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/80      2.41G      1.003      1.167     0.9687         35        640: 100% ━━━━━━━━━━━━ 91/91 5.3it/s 17.0s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.601      0.746      0.737      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/80      2.41G     0.9034      1.027     0.9435         17        640: 100% ━━━━━━━━━━━━ 91/91 5.5it/s 16.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.7it/s 1.9s0.2s
                   all        334        992      0.688       0.75        0.8       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/80      2.41G      0.888     0.9759     0.9323         32        640: 100% ━━━━━━━━━━━━ 91/91 5.5it/s 16.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.1it/s 1.8s0.2s
                   all        334        992      0.713      0.774      0.799       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/80      2.41G     0.8337     0.8944     0.9186         38        640: 100% ━━━━━━━━━━━━ 91/91 5.5it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.745      0.771      0.817      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/80      2.41G     0.7949     0.8567     0.9079         25        640: 100% ━━━━━━━━━━━━ 91/91 5.5it/s 16.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.847      0.827      0.867      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/80      2.41G     0.7883      0.832     0.9126          8        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.1it/s 1.8s0.2s
                   all        334        992      0.848      0.863      0.906      0.739

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/80      2.41G     0.7507     0.7735     0.8929         16        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.1it/s 1.8s0.2s
                   all        334        992      0.822      0.851      0.908      0.761

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/80      2.41G     0.7161     0.7444     0.8846         10        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.1it/s 1.8s0.2s
                   all        334        992      0.892      0.852      0.918      0.768

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/80      2.41G     0.7225     0.7225     0.8789         22        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.3it/s 1.7s0.2s
                   all        334        992       0.86      0.858      0.933      0.758

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/80      2.41G     0.7031      0.719     0.8787         47        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.906      0.887      0.947      0.812

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/80      2.41G     0.6908     0.6899     0.8726         37        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992       0.87      0.886      0.948      0.816

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/80      2.41G     0.6743     0.6813      0.875         30        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.873      0.862      0.907       0.78

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/80      2.41G     0.6684     0.6465     0.8699         18        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.8it/s 1.9s0.2s
                   all        334        992      0.922      0.892      0.946      0.813

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/80      2.41G     0.6642     0.6644     0.8657         29        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.877      0.878       0.93      0.806

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/80      2.41G     0.6534     0.6441     0.8669         25        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.904      0.891      0.951      0.828

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/80      2.41G     0.6366     0.6093     0.8602         39        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992       0.93      0.911      0.956      0.838

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/80      2.41G     0.6139     0.5828     0.8593         26        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.933      0.914       0.95      0.836

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/80      2.41G     0.6229     0.5983     0.8589         29        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.924      0.909      0.957      0.833

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/80      2.41G     0.6135      0.578      0.856         21        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.9it/s 1.9s0.2s
                   all        334        992      0.918      0.904      0.958      0.839

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/80      2.41G     0.5893     0.5524     0.8532         26        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.931      0.925      0.954      0.852

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/80      2.41G     0.5952     0.5725     0.8544         13        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.3it/s 1.8s0.2s
                   all        334        992      0.949      0.923      0.968      0.856

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/80      2.41G      0.579     0.5526     0.8453         18        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.3it/s 1.8s0.2s
                   all        334        992      0.919      0.909      0.943      0.837

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/80      2.41G     0.5954     0.5571     0.8517         29        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.1it/s 1.8s0.2s
                   all        334        992      0.938      0.922      0.959      0.853

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/80      2.41G     0.5749     0.5282      0.847         25        640: 100% ━━━━━━━━━━━━ 91/91 5.5it/s 16.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.3it/s 1.8s0.2s
                   all        334        992       0.95      0.931      0.975      0.871

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/80      2.41G     0.5706     0.5457     0.8469         27        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.9it/s 1.9s0.2s
                   all        334        992      0.936      0.915      0.956      0.855

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/80      2.41G      0.562     0.5297     0.8462         26        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.0it/s 1.8s0.2s
                   all        334        992      0.931      0.919      0.958      0.856

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/80      2.41G     0.5511      0.517     0.8436         35        640: 100% ━━━━━━━━━━━━ 91/91 5.5it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.922      0.938      0.967      0.875

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/80      2.41G     0.5401     0.5095     0.8384         17        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.3it/s 1.7s0.2s
                   all        334        992      0.941       0.94       0.96      0.865

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/80      2.41G     0.5527        0.5     0.8373         23        640: 100% ━━━━━━━━━━━━ 91/91 5.6it/s 16.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.2it/s 1.8s0.2s
                   all        334        992      0.946      0.925      0.966      0.877

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/80      2.41G     0.5353     0.5042     0.8432         18        640: 100% ━━━━━━━━━━━━ 91/91 5.5it/s 16.4s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 6.1it/s 1.8s0.2s
                   all        334        992      0.936      0.936      0.963      0.869

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6, 7])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000025A18793380>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,      0.7351,      0.7351,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       ...,
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,           0,           0,           0]], shape=(8, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

In [3]:
baseline_yolov8n = YOLO("runs/detect/baseline_yolov8n/weights/best.pt")

## 4. Hyperparameter Tuning

We use Ultralytics' built-in evolutionary tuner (`model.tune()`) to search for better hyperparameters.

### 4.1 Tuning YOLOv8

In [ ]:
model = YOLO("yolov8s.pt")

model.tune(
    data="./data.yaml",
    iterations=20,       
    imgsz=416,           
    batch=8,             
    epochs=15,           
    patience=5,
    optimizer="AdamW",
    plots=False,         
    save=False,          
    cache=True,
    workers=2,
    amp=True,
    name="tune_v8s"            
)

Tuner: Initialized Tuner instance with 'tune_dir=C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2'
Tuner:  Learn about tuning at https://docs.ultralytics.com/guides/hyperparameter-tuning
Tuner: Starting iteration 1/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'box': 7.5, 'cls': 0.5, 'cls_pw': 0.0, 'dfl': 1.5, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.0, 'cutmix': 0.0, 'copy_paste': 0.0, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_fitness.png

Tuner: 1/20 iterations complete  (334.26s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2
Tuner: Best fitness=0.85124 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.90806, 'metrics/recall(B)': 0.92305, 'metrics/mAP50(B)': 0.96436, 'metrics/mAP50-95(B)': 0.85124, 'val/box_loss': 0.46215, 'val/cls_loss': 0.42585, 'val/dfl_loss': 0.86799, 'fitness': 0.85124}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 2/20 with hyperparameters: {'lr0': 0.00307, 'lrf': 0.01498, 'momentum': 0.98, 'weight_decay': 0.0, 'warmup_epochs': 2.99496, 'warmup_momentum': 0.90351, 'box': 8.5523, 'cls': 0.49376, 'cls_pw': 0.0, 'dfl': 1.4582, 'hsv_h': 0.01686, 'hsv_s': 0.70279, 'hsv_v': 0.40733, 'degrees': 0.00274, 'translate': 0.10264, 'scale': 0.49611, 'shear': 0.0, 'perspective': 0.001, 'flipud': 0.0, 'fliplr': 0.399, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.00319, 'cutmix': 0.00526, 'copy_paste': 0.0, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_fitness.png

Tuner: 2/20 iterations complete  (660.33s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2
Tuner: Best fitness=0.85124 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.90806, 'metrics/recall(B)': 0.92305, 'metrics/mAP50(B)': 0.96436, 'metrics/mAP50-95(B)': 0.85124, 'val/box_loss': 0.46215, 'val/cls_loss': 0.42585, 'val/dfl_loss': 0.86799, 'fitness': 0.85124}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 3/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01132, 'momentum': 0.92889, 'weight_decay': 0.0, 'warmup_epochs': 3.00471, 'warmup_momentum': 0.73066, 'box': 7.49704, 'cls': 0.57773, 'cls_pw': 0.01576, 'dfl': 1.43882, 'hsv_h': 0.01001, 'hsv_s': 0.66091, 'hsv_v': 0.39414, 'degrees': 0.0, 'translate': 0.08876, 'scale': 0.48623, 'shear': 0.02092, 'perspective': 0.001, 'flipud': 0.00042, 'fliplr': 0.50496, 'bgr': 0.0072, 'mosaic': 0.94746, 'mixup': 0.0, 'cutmix': 0.00601, 'copy_paste': 0.00921, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_fitness.png

Tuner: 3/20 iterations complete  (986.85s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2
Tuner: Best fitness=0.85124 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.90806, 'metrics/recall(B)': 0.92305, 'metrics/mAP50(B)': 0.96436, 'metrics/mAP50-95(B)': 0.85124, 'val/box_loss': 0.46215, 'val/cls_loss': 0.42585, 'val/dfl_loss': 0.86799, 'fitness': 0.85124}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 4/20 with hyperparameters: {'lr0': 0.00429, 'lrf': 0.0155, 'momentum': 0.91496, 'weight_decay': 0.001, 'warmup_epochs': 3.0032, 'warmup_momentum': 0.793, 'box': 7.48753, 'cls': 0.49308, 'cls_pw': 0.0, 'dfl': 1.50502, 'hsv_h': 0.00983, 'hsv_s': 0.59554, 'hsv_v': 0.40887, 'degrees': 0.0, 'translate': 0.08416, 'scale': 0.50368, 'shear': 0.01323, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.61338, 'bgr': 0.0, 'mosaic': 0.97172, 'mixup': 0.01715, 'cutmix': 0.00019, 'copy_paste': 0.0073, 'close_mosaic': 9}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_fitness.png

Tuner: 4/20 iterations complete  (1306.65s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2
Tuner: Best fitness=0.87035 observed at iteration 4
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.93898, 'metrics/recall(B)': 0.92353, 'metrics/mAP50(B)': 0.97548, 'metrics/mAP50-95(B)': 0.87035, 'val/box_loss': 0.44017, 'val/cls_loss': 0.37772, 'val/dfl_loss': 0.86943, 'fitness': 0.87035}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\best_hyperparameters.yaml'

lr0: 0.00429
lrf: 0.0155
momentum: 0.91496
weight_decay: 0.001
warmup_epochs: 3.0032
warmup_momentum: 0.793
box: 7.48753
cls: 0.49308
cls_pw: 0.0
dfl: 1.50502
hsv_h: 0.00983
hsv_s: 0.59554
hsv_v: 0.40887
degrees: 0.0
translate: 0.08416
scale: 0.50368
shear: 0.01323
perspective: 0.0
flipud: 0.0
fliplr: 0.61338
bgr: 0.0
mosaic: 0.97172
mixup: 0.01715
cutmix: 0.00019
copy_paste: 0.0073
close_mosaic: 9

Tuner: Starting iteration 5/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01662, 'momentum': 0.89567, 'weight_decay': 0.0, 'warmup_epochs': 2.86787, 'warmup_momentum': 0.78686, 'box': 7.5087, 'cls': 0.50237, 'cls_pw': 0.00564, 'dfl': 1.57282, 'hsv_h': 0.00859, 'hsv_s': 0.9, 'hsv_v': 0.41284, 'degrees': 0.0, 'translate': 0.10212, 'scale': 0.49684, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.49673, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.01508, 'cutmix': 0.00527, 'copy_paste': 0.0, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_fitness.png

Tuner: 5/20 iterations complete  (1625.38s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2
Tuner: Best fitness=0.87035 observed at iteration 4
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.93898, 'metrics/recall(B)': 0.92353, 'metrics/mAP50(B)': 0.97548, 'metrics/mAP50-95(B)': 0.87035, 'val/box_loss': 0.44017, 'val/cls_loss': 0.37772, 'val/dfl_loss': 0.86943, 'fitness': 0.87035}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\best_hyperparameters.yaml'

lr0: 0.00429
lrf: 0.0155
momentum: 0.91496
weight_decay: 0.001
warmup_epochs: 3.0032
warmup_momentum: 0.793
box: 7.48753
cls: 0.49308
cls_pw: 0.0
dfl: 1.50502
hsv_h: 0.00983
hsv_s: 0.59554
hsv_v: 0.40887
degrees: 0.0
translate: 0.08416
scale: 0.50368
shear: 0.01323
perspective: 0.0
flipud: 0.0
fliplr: 0.61338
bgr: 0.0
mosaic: 0.97172
mixup: 0.01715
cutmix: 0.00019
copy_paste: 0.0073
close_mosaic: 9

Tuner: Starting iteration 6/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01176, 'momentum': 0.8895, 'weight_decay': 0.00084, 'warmup_epochs': 3.085, 'warmup_momentum': 0.6009, 'box': 8.0201, 'cls': 0.50717, 'cls_pw': 0.0, 'dfl': 1.48822, 'hsv_h': 0.01112, 'hsv_s': 0.40678, 'hsv_v': 0.36856, 'degrees': 0.0, 'translate': 0.064, 'scale': 0.49659, 'shear': 0.01087, 'perspective': 0.001, 'flipud': 0.00575, 'fliplr': 0.62901, 'bgr': 0.00618, 'mosaic': 0.75173, 'mixup': 0.01951, 'cutmix': 0.00148, 'copy_paste': 0.0014, 'close_mosaic': 8}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_fitness.png

Tuner: 6/20 iterations complete  (1942.40s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2
Tuner: Best fitness=0.87035 observed at iteration 4
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.93898, 'metrics/recall(B)': 0.92353, 'metrics/mAP50(B)': 0.97548, 'metrics/mAP50-95(B)': 0.87035, 'val/box_loss': 0.44017, 'val/cls_loss': 0.37772, 'val/dfl_loss': 0.86943, 'fitness': 0.87035}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\best_hyperparameters.yaml'

lr0: 0.00429
lrf: 0.0155
momentum: 0.91496
weight_decay: 0.001
warmup_epochs: 3.0032
warmup_momentum: 0.793
box: 7.48753
cls: 0.49308
cls_pw: 0.0
dfl: 1.50502
hsv_h: 0.00983
hsv_s: 0.59554
hsv_v: 0.40887
degrees: 0.0
translate: 0.08416
scale: 0.50368
shear: 0.01323
perspective: 0.0
flipud: 0.0
fliplr: 0.61338
bgr: 0.0
mosaic: 0.97172
mixup: 0.01715
cutmix: 0.00019
copy_paste: 0.0073
close_mosaic: 9

Tuner: Starting iteration 7/20 with hyperparameters: {'lr0': 0.00372, 'lrf': 0.01754, 'momentum': 0.90631, 'weight_decay': 0.00065, 'warmup_epochs': 2.83304, 'warmup_momentum': 0.7937, 'box': 7.48536, 'cls': 0.57664, 'cls_pw': 0.00565, 'dfl': 1.71717, 'hsv_h': 0.01285, 'hsv_s': 0.65137, 'hsv_v': 0.40792, 'degrees': 0.00565, 'translate': 0.07918, 'scale': 0.49684, 'shear': 0.01041, 'perspective': 0.0, 'flipud': 0.00249, 'fliplr': 0.5916, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.01668, 'cutmix': 0.00104, 'copy_paste': 0.00743, 'close_mosaic': 9}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_fitness.png

Tuner: 7/20 iterations complete  (2260.62s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2
Tuner: Best fitness=0.87035 observed at iteration 4
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.93898, 'metrics/recall(B)': 0.92353, 'metrics/mAP50(B)': 0.97548, 'metrics/mAP50-95(B)': 0.87035, 'val/box_loss': 0.44017, 'val/cls_loss': 0.37772, 'val/dfl_loss': 0.86943, 'fitness': 0.87035}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\best_hyperparameters.yaml'

lr0: 0.00429
lrf: 0.0155
momentum: 0.91496
weight_decay: 0.001
warmup_epochs: 3.0032
warmup_momentum: 0.793
box: 7.48753
cls: 0.49308
cls_pw: 0.0
dfl: 1.50502
hsv_h: 0.00983
hsv_s: 0.59554
hsv_v: 0.40887
degrees: 0.0
translate: 0.08416
scale: 0.50368
shear: 0.01323
perspective: 0.0
flipud: 0.0
fliplr: 0.61338
bgr: 0.0
mosaic: 0.97172
mixup: 0.01715
cutmix: 0.00019
copy_paste: 0.0073
close_mosaic: 9

Tuner: Starting iteration 8/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.02818, 'momentum': 0.91174, 'weight_decay': 5e-05, 'warmup_epochs': 2.8789, 'warmup_momentum': 0.82108, 'box': 6.55343, 'cls': 0.78461, 'cls_pw': 0.00566, 'dfl': 1.73107, 'hsv_h': 0.01384, 'hsv_s': 0.9, 'hsv_v': 0.41296, 'degrees': 0.00205, 'translate': 0.07615, 'scale': 0.50468, 'shear': 0.01441, 'perspective': 0.001, 'flipud': 0.00034, 'fliplr': 0.57868, 'bgr': 0.00351, 'mosaic': 0.98282, 'mixup': 0.02521, 'cutmix': 0.00131, 'copy_paste': 0.00477, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_fitness.png

Tuner: 8/20 iterations complete  (2576.28s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2
Tuner: Best fitness=0.87035 observed at iteration 4
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.93898, 'metrics/recall(B)': 0.92353, 'metrics/mAP50(B)': 0.97548, 'metrics/mAP50-95(B)': 0.87035, 'val/box_loss': 0.44017, 'val/cls_loss': 0.37772, 'val/dfl_loss': 0.86943, 'fitness': 0.87035}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\best_hyperparameters.yaml'

lr0: 0.00429
lrf: 0.0155
momentum: 0.91496
weight_decay: 0.001
warmup_epochs: 3.0032
warmup_momentum: 0.793
box: 7.48753
cls: 0.49308
cls_pw: 0.0
dfl: 1.50502
hsv_h: 0.00983
hsv_s: 0.59554
hsv_v: 0.40887
degrees: 0.0
translate: 0.08416
scale: 0.50368
shear: 0.01323
perspective: 0.0
flipud: 0.0
fliplr: 0.61338
bgr: 0.0
mosaic: 0.97172
mixup: 0.01715
cutmix: 0.00019
copy_paste: 0.0073
close_mosaic: 9

Tuner: Starting iteration 9/20 with hyperparameters: {'lr0': 0.00837, 'lrf': 0.01032, 'momentum': 0.92697, 'weight_decay': 0.00064, 'warmup_epochs': 2.78458, 'warmup_momentum': 0.81468, 'box': 7.3832, 'cls': 0.531, 'cls_pw': 0.0059, 'dfl': 1.77287, 'hsv_h': 0.01177, 'hsv_s': 0.9, 'hsv_v': 0.39686, 'degrees': 0.00421, 'translate': 0.10388, 'scale': 0.52246, 'shear': 0.00605, 'perspective': 0.0, 'flipud': 0.00346, 'fliplr': 0.41449, 'bgr': 0.00828, 'mosaic': 0.91627, 'mixup': 0.00171, 'cutmix': 0.00294, 'copy_paste': 0.0, 'close_mosaic': 8}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_fitness.png

Tuner: 9/20 iterations complete  (2890.21s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2
Tuner: Best fitness=0.87035 observed at iteration 4
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.93898, 'metrics/recall(B)': 0.92353, 'metrics/mAP50(B)': 0.97548, 'metrics/mAP50-95(B)': 0.87035, 'val/box_loss': 0.44017, 'val/cls_loss': 0.37772, 'val/dfl_loss': 0.86943, 'fitness': 0.87035}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\best_hyperparameters.yaml'

lr0: 0.00429
lrf: 0.0155
momentum: 0.91496
weight_decay: 0.001
warmup_epochs: 3.0032
warmup_momentum: 0.793
box: 7.48753
cls: 0.49308
cls_pw: 0.0
dfl: 1.50502
hsv_h: 0.00983
hsv_s: 0.59554
hsv_v: 0.40887
degrees: 0.0
translate: 0.08416
scale: 0.50368
shear: 0.01323
perspective: 0.0
flipud: 0.0
fliplr: 0.61338
bgr: 0.0
mosaic: 0.97172
mixup: 0.01715
cutmix: 0.00019
copy_paste: 0.0073
close_mosaic: 9

Tuner: Starting iteration 10/20 with hyperparameters: {'lr0': 0.00901, 'lrf': 0.0166, 'momentum': 0.90457, 'weight_decay': 4e-05, 'warmup_epochs': 2.93305, 'warmup_momentum': 0.89661, 'box': 5.79933, 'cls': 0.52379, 'cls_pw': 0.0, 'dfl': 1.79233, 'hsv_h': 0.00788, 'hsv_s': 0.43347, 'hsv_v': 0.39422, 'degrees': 0.00291, 'translate': 0.0666, 'scale': 0.49912, 'shear': 0.0, 'perspective': 0.001, 'flipud': 0.0027, 'fliplr': 0.58325, 'bgr': 2e-05, 'mosaic': 1.0, 'mixup': 0.02227, 'cutmix': 0.00581, 'copy_paste': 0.00618, 'close_mosaic': 9}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\tune_fitness.png

Tuner: 10/20 iterations complete  (3202.99s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2
Tuner: Best fitness=0.87035 observed at iteration 4
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.93898, 'metrics/recall(B)': 0.92353, 'metrics/mAP50(B)': 0.97548, 'metrics/mAP50-95(B)': 0.87035, 'val/box_loss': 0.44017, 'val/cls_loss': 0.37772, 'val/dfl_loss': 0.86943, 'fitness': 0.87035}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune2\best_hyperparameters.yaml'

lr0: 0.00429
lrf: 0.0155
momentum: 0.91496
weight_decay: 0.001
warmup_epochs: 3.0032
warmup_momentum: 0.793
box: 7.48753
cls: 0.49308
cls_pw: 0.0
dfl: 1.50502
hsv_h: 0.00983
hsv_s: 0.59554
hsv_v: 0.40887
degrees: 0.0
translate: 0.08416
scale: 0.50368
shear: 0.01323
perspective: 0.0
flipud: 0.0
fliplr: 0.61338
bgr: 0.0
mosaic: 0.97172
mixup: 0.01715
cutmix: 0.00019
copy_paste: 0.0073
close_mosaic: 9

Tuner: Starting iteration 11/20 with hyperparameters: {'lr0': 0.00756, 'lrf': 0.0142, 'momentum': 0.956, 'weight_decay': 0.0, 'warmup_epochs': 2.8491, 'warmup_momentum': 0.91441, 'box': 7.7917, 'cls': 0.71212, 'cls_pw': 0.00337, 'dfl': 1.23909, 'hsv_h': 0.01661, 'hsv_s': 0.69761, 'hsv_v': 0.28619, 'degrees': 0.00057, 'translate': 0.1083, 'scale': 0.47577, 'shear': 0.0039, 'perspective': 0.00097, 'flipud': 0.00144, 'fliplr': 0.62052, 'bgr': 0.00707, 'mosaic': 1.0, 'mixup': 0.00721, 'cutmix': 0.00339, 'copy_paste': 0.00447, 'close_mosaic': 9}
ERROR training failure for hyperparameter tuning iteration 11

### 4.2 Tuning YOLOv11

In [11]:
model = YOLO("yolo11s.pt")

model.tune(
    data="./data.yaml",
    iterations=20,
    imgsz=416,
    batch=8,
    epochs=15,
    patience=5,
    optimizer="AdamW", 
    plots=False,
    save=False,
    cache=True,
    workers=2,
    amp=True,
    name="tune_v11s"
)

Tuner: Initialized Tuner instance with 'tune_dir=C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3'
Tuner:  Learn about tuning at https://docs.ultralytics.com/guides/hyperparameter-tuning
Tuner: Starting iteration 1/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'box': 7.5, 'cls': 0.5, 'cls_pw': 0.0, 'dfl': 1.5, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.0, 'cutmix': 0.0, 'copy_paste': 0.0, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_fitness.png

Tuner: 1/20 iterations complete  (362.26s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3
Tuner: Best fitness=0.84505 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9248, 'metrics/recall(B)': 0.90804, 'metrics/mAP50(B)': 0.95799, 'metrics/mAP50-95(B)': 0.84505, 'val/box_loss': 0.47908, 'val/cls_loss': 0.44256, 'val/dfl_loss': 0.87395, 'fitness': 0.84505}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 2/20 with hyperparameters: {'lr0': 0.00695, 'lrf': 0.01, 'momentum': 0.98, 'weight_decay': 0.0005, 'warmup_epochs': 3.00053, 'warmup_momentum': 0.75244, 'box': 7.50148, 'cls': 0.46571, 'cls_pw': 0.0, 'dfl': 1.44381, 'hsv_h': 0.01626, 'hsv_s': 0.57931, 'hsv_v': 0.4181, 'degrees': 0.00084, 'translate': 0.09012, 'scale': 0.57312, 'shear': 0.00681, 'perspective': 0.00016, 'flipud': 0.0, 'fliplr': 0.51263, 'bgr': 0.00341, 'mosaic': 1.0, 'mixup': 0.0, 'cutmix': 0.0, 'copy_paste': 0.0, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_fitness.png

Tuner: 2/20 iterations complete  (721.77s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3
Tuner: Best fitness=0.84505 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9248, 'metrics/recall(B)': 0.90804, 'metrics/mAP50(B)': 0.95799, 'metrics/mAP50-95(B)': 0.84505, 'val/box_loss': 0.47908, 'val/cls_loss': 0.44256, 'val/dfl_loss': 0.87395, 'fitness': 0.84505}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 3/20 with hyperparameters: {'lr0': 1e-05, 'lrf': 0.01759, 'momentum': 0.93581, 'weight_decay': 0.001, 'warmup_epochs': 2.31176, 'warmup_momentum': 0.80146, 'box': 8.04726, 'cls': 0.6821, 'cls_pw': 0.0169, 'dfl': 1.51597, 'hsv_h': 0.00472, 'hsv_s': 0.69337, 'hsv_v': 0.40329, 'degrees': 0.00556, 'translate': 0.07197, 'scale': 0.66271, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.00473, 'fliplr': 0.46506, 'bgr': 0.0, 'mosaic': 0.8979, 'mixup': 0.0, 'cutmix': 0.0, 'copy_paste': 0.00805, 'close_mosaic': 7}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_fitness.png

Tuner: 3/20 iterations complete  (1076.06s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3
Tuner: Best fitness=0.84505 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9248, 'metrics/recall(B)': 0.90804, 'metrics/mAP50(B)': 0.95799, 'metrics/mAP50-95(B)': 0.84505, 'val/box_loss': 0.47908, 'val/cls_loss': 0.44256, 'val/dfl_loss': 0.87395, 'fitness': 0.84505}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 4/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.98, 'weight_decay': 0.001, 'warmup_epochs': 3.00027, 'warmup_momentum': 0.79172, 'box': 7.50176, 'cls': 0.46169, 'cls_pw': 0.00717, 'dfl': 1.17743, 'hsv_h': 0.01693, 'hsv_s': 0.64329, 'hsv_v': 0.40096, 'degrees': 5e-05, 'translate': 0.09807, 'scale': 0.57331, 'shear': 0.00439, 'perspective': 0.0, 'flipud': 0.00473, 'fliplr': 0.81909, 'bgr': 0.00033, 'mosaic': 1.0, 'mixup': 0.01085, 'cutmix': 0.00494, 'copy_paste': 0.0099, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_fitness.png

Tuner: 4/20 iterations complete  (1437.35s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3
Tuner: Best fitness=0.84505 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9248, 'metrics/recall(B)': 0.90804, 'metrics/mAP50(B)': 0.95799, 'metrics/mAP50-95(B)': 0.84505, 'val/box_loss': 0.47908, 'val/cls_loss': 0.44256, 'val/dfl_loss': 0.87395, 'fitness': 0.84505}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 5/20 with hyperparameters: {'lr0': 0.00943, 'lrf': 0.01, 'momentum': 0.98, 'weight_decay': 0.0, 'warmup_epochs': 3.00009, 'warmup_momentum': 0.95, 'box': 7.58893, 'cls': 0.48515, 'cls_pw': 0.00129, 'dfl': 1.46333, 'hsv_h': 0.01786, 'hsv_s': 0.75082, 'hsv_v': 0.39776, 'degrees': 0.00064, 'translate': 0.06576, 'scale': 0.46928, 'shear': 0.00707, 'perspective': 3e-05, 'flipud': 0.00726, 'fliplr': 0.51479, 'bgr': 0.00013, 'mosaic': 0.94959, 'mixup': 0.01058, 'cutmix': 0.0, 'copy_paste': 0.00393, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_fitness.png

Tuner: 5/20 iterations complete  (1795.56s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3
Tuner: Best fitness=0.84505 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9248, 'metrics/recall(B)': 0.90804, 'metrics/mAP50(B)': 0.95799, 'metrics/mAP50-95(B)': 0.84505, 'val/box_loss': 0.47908, 'val/cls_loss': 0.44256, 'val/dfl_loss': 0.87395, 'fitness': 0.84505}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 6/20 with hyperparameters: {'lr0': 0.00727, 'lrf': 0.01, 'momentum': 0.93563, 'weight_decay': 0.001, 'warmup_epochs': 2.99995, 'warmup_momentum': 0.74289, 'box': 11.74306, 'cls': 0.70625, 'cls_pw': 0.00325, 'dfl': 1.41375, 'hsv_h': 0.01545, 'hsv_s': 0.64232, 'hsv_v': 0.37185, 'degrees': 0.00037, 'translate': 0.06007, 'scale': 0.48765, 'shear': 0.00144, 'perspective': 0.00013, 'flipud': 0.0, 'fliplr': 0.74298, 'bgr': 0.00128, 'mosaic': 0.68517, 'mixup': 0.00215, 'cutmix': 0.00222, 'copy_paste': 0.0, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_fitness.png

Tuner: 6/20 iterations complete  (2143.55s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3
Tuner: Best fitness=0.84505 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9248, 'metrics/recall(B)': 0.90804, 'metrics/mAP50(B)': 0.95799, 'metrics/mAP50-95(B)': 0.84505, 'val/box_loss': 0.47908, 'val/cls_loss': 0.44256, 'val/dfl_loss': 0.87395, 'fitness': 0.84505}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 7/20 with hyperparameters: {'lr0': 0.00748, 'lrf': 0.01128, 'momentum': 0.98, 'weight_decay': 0.00095, 'warmup_epochs': 1.98178, 'warmup_momentum': 0.77829, 'box': 12.15995, 'cls': 0.45884, 'cls_pw': 0.0, 'dfl': 0.95733, 'hsv_h': 0.01475, 'hsv_s': 0.9, 'hsv_v': 0.39712, 'degrees': 0.0, 'translate': 0.06458, 'scale': 0.47943, 'shear': 0.00542, 'perspective': 0.00026, 'flipud': 0.01156, 'fliplr': 0.46928, 'bgr': 0.00167, 'mosaic': 0.69278, 'mixup': 0.0, 'cutmix': 0.00297, 'copy_paste': 0.00424, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_fitness.png

Tuner: 7/20 iterations complete  (2486.92s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3
Tuner: Best fitness=0.84505 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9248, 'metrics/recall(B)': 0.90804, 'metrics/mAP50(B)': 0.95799, 'metrics/mAP50-95(B)': 0.84505, 'val/box_loss': 0.47908, 'val/cls_loss': 0.44256, 'val/dfl_loss': 0.87395, 'fitness': 0.84505}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 8/20 with hyperparameters: {'lr0': 0.00694, 'lrf': 0.01, 'momentum': 0.98, 'weight_decay': 0.0, 'warmup_epochs': 2.9107, 'warmup_momentum': 0.90302, 'box': 8.25129, 'cls': 0.47899, 'cls_pw': 0.0037, 'dfl': 1.20533, 'hsv_h': 0.01779, 'hsv_s': 0.50618, 'hsv_v': 0.33091, 'degrees': 0.0, 'translate': 0.1001, 'scale': 0.58262, 'shear': 0.0011, 'perspective': 0.00027, 'flipud': 0.00131, 'fliplr': 0.51182, 'bgr': 0.00271, 'mosaic': 0.93787, 'mixup': 0.0115, 'cutmix': 0.00239, 'copy_paste': 0.00443, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_fitness.png

Tuner: 8/20 iterations complete  (2826.82s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3
Tuner: Best fitness=0.84505 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9248, 'metrics/recall(B)': 0.90804, 'metrics/mAP50(B)': 0.95799, 'metrics/mAP50-95(B)': 0.84505, 'val/box_loss': 0.47908, 'val/cls_loss': 0.44256, 'val/dfl_loss': 0.87395, 'fitness': 0.84505}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 9/20 with hyperparameters: {'lr0': 0.00738, 'lrf': 0.01065, 'momentum': 0.96458, 'weight_decay': 0.0, 'warmup_epochs': 3.0381, 'warmup_momentum': 0.95, 'box': 6.71966, 'cls': 0.57987, 'cls_pw': 0.0, 'dfl': 1.44753, 'hsv_h': 0.01742, 'hsv_s': 0.9, 'hsv_v': 0.24765, 'degrees': 0.0005, 'translate': 0.10644, 'scale': 0.6959, 'shear': 0.00918, 'perspective': 0.00024, 'flipud': 0.00577, 'fliplr': 0.859, 'bgr': 0.00034, 'mosaic': 0.76198, 'mixup': 0.0019, 'cutmix': 0.00594, 'copy_paste': 0.00079, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_fitness.png

Tuner: 9/20 iterations complete  (3168.85s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3
Tuner: Best fitness=0.84505 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9248, 'metrics/recall(B)': 0.90804, 'metrics/mAP50(B)': 0.95799, 'metrics/mAP50-95(B)': 0.84505, 'val/box_loss': 0.47908, 'val/cls_loss': 0.44256, 'val/dfl_loss': 0.87395, 'fitness': 0.84505}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 10/20 with hyperparameters: {'lr0': 0.00773, 'lrf': 0.01295, 'momentum': 0.98, 'weight_decay': 0.00049, 'warmup_epochs': 1.82935, 'warmup_momentum': 0.95, 'box': 8.49047, 'cls': 0.6313, 'cls_pw': 0.00107, 'dfl': 0.89465, 'hsv_h': 0.0161, 'hsv_s': 0.9, 'hsv_v': 0.35225, 'degrees': 0.00051, 'translate': 0.07604, 'scale': 0.59904, 'shear': 0.00227, 'perspective': 7e-05, 'flipud': 0.0, 'fliplr': 0.41219, 'bgr': 0.00269, 'mosaic': 0.69218, 'mixup': 0.0, 'cutmix': 0.00346, 'copy_paste': 0.00084, 'close_mosaic': 8}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_fitness.png

Tuner: 10/20 iterations complete  (3523.35s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3
Tuner: Best fitness=0.84505 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9248, 'metrics/recall(B)': 0.90804, 'metrics/mAP50(B)': 0.95799, 'metrics/mAP50-95(B)': 0.84505, 'val/box_loss': 0.47908, 'val/cls_loss': 0.44256, 'val/dfl_loss': 0.87395, 'fitness': 0.84505}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 11/20 with hyperparameters: {'lr0': 0.00498, 'lrf': 0.0124, 'momentum': 0.92807, 'weight_decay': 0.00059, 'warmup_epochs': 1.95843, 'warmup_momentum': 0.83069, 'box': 7.02654, 'cls': 0.54536, 'cls_pw': 0.0, 'dfl': 2.15756, 'hsv_h': 0.01821, 'hsv_s': 0.9, 'hsv_v': 0.39293, 'degrees': 0.00031, 'translate': 0.05734, 'scale': 0.60928, 'shear': 0.00526, 'perspective': 8e-05, 'flipud': 0.00487, 'fliplr': 0.67182, 'bgr': 0.00112, 'mosaic': 0.9908, 'mixup': 0.0, 'cutmix': 0.00415, 'copy_paste': 0.0043, 'close_mosaic': 7}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\tune_fitness.png

Tuner: 11/20 iterations complete  (3877.99s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3
Tuner: Best fitness=0.84505 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9248, 'metrics/recall(B)': 0.90804, 'metrics/mAP50(B)': 0.95799, 'metrics/mAP50-95(B)': 0.84505, 'val/box_loss': 0.47908, 'val/cls_loss': 0.44256, 'val/dfl_loss': 0.87395, 'fitness': 0.84505}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune3\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10


### 4.3 Tuning YOLOv26

In [12]:
model = YOLO("yolo26s.pt")

model.tune(
    data="./data.yaml",
    iterations=20,
    imgsz=416,
    batch=8,
    epochs=15,
    patience=5,
    optimizer="auto",  
    plots=False,
    save=False,
    cache=True,
    workers=2,
    amp=True,
    name="tune_v26s"
)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26s.pt to 'yolo26s.pt': 100% ━━━━━━━━━━━━ 19.5MB 13.5MB/s 1.4s1.4s<0.1sss
Tuner: Initialized Tuner instance with 'tune_dir=C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s'
Tuner:  Learn about tuning at https://docs.ultralytics.com/guides/hyperparameter-tuning
Tuner: Starting iteration 1/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'box': 7.5, 'cls': 0.5, 'cls_pw': 0.0, 'dfl': 1.5, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.0, 'cutmix': 0.0, 'copy_paste': 0.0, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_fitness.png

Tuner: 1/20 iterations complete  (450.70s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s
Tuner: Best fitness=0.8452 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.92949, 'metrics/recall(B)': 0.93745, 'metrics/mAP50(B)': 0.9643, 'metrics/mAP50-95(B)': 0.8452, 'val/box_loss': 0.48098, 'val/cls_loss': 0.30717, 'val/dfl_loss': 0.00244, 'fitness': 0.8452}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 2/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.95121, 'weight_decay': 0.0, 'warmup_epochs': 3.01286, 'warmup_momentum': 0.66406, 'box': 7.49671, 'cls': 0.50918, 'cls_pw': 0.0, 'dfl': 1.51114, 'hsv_h': 0.01609, 'hsv_s': 0.69871, 'hsv_v': 0.50202, 'degrees': 0.0, 'translate': 0.09849, 'scale': 0.49856, 'shear': 0.00115, 'perspective': 0.001, 'flipud': 0.0, 'fliplr': 0.53342, 'bgr': 0.00153, 'mosaic': 1.0, 'mixup': 0.0, 'cutmix': 0.0, 'copy_paste': 0.0, 'close_mosaic': 8}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_fitness.png

Tuner: 2/20 iterations complete  (883.98s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s
Tuner: Best fitness=0.8452 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.92949, 'metrics/recall(B)': 0.93745, 'metrics/mAP50(B)': 0.9643, 'metrics/mAP50-95(B)': 0.8452, 'val/box_loss': 0.48098, 'val/cls_loss': 0.30717, 'val/dfl_loss': 0.00244, 'fitness': 0.8452}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 3/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.94162, 'weight_decay': 0.001, 'warmup_epochs': 3.00584, 'warmup_momentum': 0.78942, 'box': 10.63203, 'cls': 0.50116, 'cls_pw': 0.00534, 'dfl': 1.49792, 'hsv_h': 0.01175, 'hsv_s': 0.53961, 'hsv_v': 0.40684, 'degrees': 0.0, 'translate': 0.11159, 'scale': 0.48863, 'shear': 0.00031, 'perspective': 0.001, 'flipud': 0.02164, 'fliplr': 0.41504, 'bgr': 0.0, 'mosaic': 0.99418, 'mixup': 0.0, 'cutmix': 0.0166, 'copy_paste': 0.0, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_fitness.png

Tuner: 3/20 iterations complete  (1324.29s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s
Tuner: Best fitness=0.8452 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.92949, 'metrics/recall(B)': 0.93745, 'metrics/mAP50(B)': 0.9643, 'metrics/mAP50-95(B)': 0.8452, 'val/box_loss': 0.48098, 'val/cls_loss': 0.30717, 'val/dfl_loss': 0.00244, 'fitness': 0.8452}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 4/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.92409, 'weight_decay': 0.001, 'warmup_epochs': 3.21588, 'warmup_momentum': 0.79784, 'box': 7.37791, 'cls': 0.58992, 'cls_pw': 0.0, 'dfl': 1.49731, 'hsv_h': 0.02489, 'hsv_s': 0.58599, 'hsv_v': 0.29875, 'degrees': 6e-05, 'translate': 0.15702, 'scale': 0.50152, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.00204, 'fliplr': 0.51711, 'bgr': 0.0071, 'mosaic': 1.0, 'mixup': 0.0, 'cutmix': 0.0098, 'copy_paste': 0.0, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_fitness.png

Tuner: 4/20 iterations complete  (1734.94s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s
Tuner: Best fitness=0.8452 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.92949, 'metrics/recall(B)': 0.93745, 'metrics/mAP50(B)': 0.9643, 'metrics/mAP50-95(B)': 0.8452, 'val/box_loss': 0.48098, 'val/cls_loss': 0.30717, 'val/dfl_loss': 0.00244, 'fitness': 0.8452}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 5/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.02381, 'momentum': 0.92281, 'weight_decay': 0.00081, 'warmup_epochs': 3.23487, 'warmup_momentum': 0.79754, 'box': 7.13536, 'cls': 0.40818, 'cls_pw': 0.01561, 'dfl': 1.72684, 'hsv_h': 0.02786, 'hsv_s': 0.69704, 'hsv_v': 0.30651, 'degrees': 0.0, 'translate': 0.15389, 'scale': 0.55269, 'shear': 0.0, 'perspective': 0.001, 'flipud': 0.0, 'fliplr': 0.50706, 'bgr': 0.00404, 'mosaic': 1.0, 'mixup': 0.0, 'cutmix': 0.00325, 'copy_paste': 0.00265, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_fitness.png

Tuner: 5/20 iterations complete  (2152.66s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s
Tuner: Best fitness=0.8452 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.92949, 'metrics/recall(B)': 0.93745, 'metrics/mAP50(B)': 0.9643, 'metrics/mAP50-95(B)': 0.8452, 'val/box_loss': 0.48098, 'val/cls_loss': 0.30717, 'val/dfl_loss': 0.00244, 'fitness': 0.8452}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 6/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.93599, 'weight_decay': 0.00065, 'warmup_epochs': 3.00633, 'warmup_momentum': 0.65054, 'box': 7.49829, 'cls': 0.50734, 'cls_pw': 0.00317, 'dfl': 1.5054, 'hsv_h': 0.01896, 'hsv_s': 0.84053, 'hsv_v': 0.36527, 'degrees': 0.01, 'translate': 0.09937, 'scale': 0.49943, 'shear': 0.0015, 'perspective': 0.00042, 'flipud': 0.01215, 'fliplr': 0.50161, 'bgr': 0.00085, 'mosaic': 1.0, 'mixup': 0.00033, 'cutmix': 0.00107, 'copy_paste': 0.00544, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_fitness.png

Tuner: 6/20 iterations complete  (2592.06s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s
Tuner: Best fitness=0.8452 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.92949, 'metrics/recall(B)': 0.93745, 'metrics/mAP50(B)': 0.9643, 'metrics/mAP50-95(B)': 0.8452, 'val/box_loss': 0.48098, 'val/cls_loss': 0.30717, 'val/dfl_loss': 0.00244, 'fitness': 0.8452}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
cls_pw: 0.0
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
close_mosaic: 10

Tuner: Starting iteration 7/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.97292, 'weight_decay': 0.00087, 'warmup_epochs': 2.6614, 'warmup_momentum': 0.95, 'box': 5.82995, 'cls': 0.41902, 'cls_pw': 0.00249, 'dfl': 1.50655, 'hsv_h': 0.01865, 'hsv_s': 0.89924, 'hsv_v': 0.382, 'degrees': 0.01146, 'translate': 0.16207, 'scale': 0.49959, 'shear': 0.00049, 'perspective': 1e-05, 'flipud': 0.00903, 'fliplr': 0.64909, 'bgr': 0.00299, 'mosaic': 1.0, 'mixup': 8e-05, 'cutmix': 0.0, 'copy_paste': 0.00455, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_fitness.png

Tuner: 7/20 iterations complete  (3031.74s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s
Tuner: Best fitness=0.85137 observed at iteration 7
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9151, 'metrics/recall(B)': 0.93526, 'metrics/mAP50(B)': 0.96585, 'metrics/mAP50-95(B)': 0.85137, 'val/box_loss': 0.37397, 'val/cls_loss': 0.26148, 'val/dfl_loss': 0.00245, 'fitness': 0.85137}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.97292
weight_decay: 0.00087
warmup_epochs: 2.6614
warmup_momentum: 0.95
box: 5.82995
cls: 0.41902
cls_pw: 0.00249
dfl: 1.50655
hsv_h: 0.01865
hsv_s: 0.89924
hsv_v: 0.382
degrees: 0.01146
translate: 0.16207
scale: 0.49959
shear: 0.00049
perspective: 1.0e-05
flipud: 0.00903
fliplr: 0.64909
bgr: 0.00299
mosaic: 1.0
mixup: 8.0e-05
cutmix: 0.0
copy_paste: 0.00455
close_mosaic: 10

Tuner: Starting iteration 8/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.0287, 'momentum': 0.94936, 'weight_decay': 0.0, 'warmup_epochs': 2.14169, 'warmup_momentum': 0.7777, 'box': 5.88244, 'cls': 0.45795, 'cls_pw': 0.00184, 'dfl': 1.5027, 'hsv_h': 0.01697, 'hsv_s': 0.7627, 'hsv_v': 0.37072, 'degrees': 0.00025, 'translate': 0.1363, 'scale': 0.35233, 'shear': 0.0, 'perspective': 0.0005, 'flipud': 0.00707, 'fliplr': 0.67463, 'bgr': 0.00099, 'mosaic': 0.9936, 'mixup': 0.0, 'cutmix': 0.00049, 'copy_paste': 0.00468, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_fitness.png

Tuner: 8/20 iterations complete  (3475.72s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s
Tuner: Best fitness=0.85137 observed at iteration 7
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9151, 'metrics/recall(B)': 0.93526, 'metrics/mAP50(B)': 0.96585, 'metrics/mAP50-95(B)': 0.85137, 'val/box_loss': 0.37397, 'val/cls_loss': 0.26148, 'val/dfl_loss': 0.00245, 'fitness': 0.85137}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.97292
weight_decay: 0.00087
warmup_epochs: 2.6614
warmup_momentum: 0.95
box: 5.82995
cls: 0.41902
cls_pw: 0.00249
dfl: 1.50655
hsv_h: 0.01865
hsv_s: 0.89924
hsv_v: 0.382
degrees: 0.01146
translate: 0.16207
scale: 0.49959
shear: 0.00049
perspective: 1.0e-05
flipud: 0.00903
fliplr: 0.64909
bgr: 0.00299
mosaic: 1.0
mixup: 8.0e-05
cutmix: 0.0
copy_paste: 0.00455
close_mosaic: 10

Tuner: Starting iteration 9/20 with hyperparameters: {'lr0': 0.00605, 'lrf': 0.01888, 'momentum': 0.95325, 'weight_decay': 0.00018, 'warmup_epochs': 3.37348, 'warmup_momentum': 0.69569, 'box': 7.09133, 'cls': 0.30429, 'cls_pw': 0.00178, 'dfl': 1.35006, 'hsv_h': 0.01413, 'hsv_s': 0.87678, 'hsv_v': 0.37553, 'degrees': 0.00351, 'translate': 0.12927, 'scale': 0.44105, 'shear': 0.0005, 'perspective': 0.00037, 'flipud': 0.00252, 'fliplr': 0.71568, 'bgr': 0.0, 'mosaic': 0.99667, 'mixup': 0.0, 'cutmix': 0.00734, 'copy_paste': 0.00645, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_fitness.png

Tuner: 9/20 iterations complete  (3918.73s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s
Tuner: Best fitness=0.85137 observed at iteration 7
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9151, 'metrics/recall(B)': 0.93526, 'metrics/mAP50(B)': 0.96585, 'metrics/mAP50-95(B)': 0.85137, 'val/box_loss': 0.37397, 'val/cls_loss': 0.26148, 'val/dfl_loss': 0.00245, 'fitness': 0.85137}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.97292
weight_decay: 0.00087
warmup_epochs: 2.6614
warmup_momentum: 0.95
box: 5.82995
cls: 0.41902
cls_pw: 0.00249
dfl: 1.50655
hsv_h: 0.01865
hsv_s: 0.89924
hsv_v: 0.382
degrees: 0.01146
translate: 0.16207
scale: 0.49959
shear: 0.00049
perspective: 1.0e-05
flipud: 0.00903
fliplr: 0.64909
bgr: 0.00299
mosaic: 1.0
mixup: 8.0e-05
cutmix: 0.0
copy_paste: 0.00455
close_mosaic: 10

Tuner: Starting iteration 10/20 with hyperparameters: {'lr0': 0.00933, 'lrf': 0.01865, 'momentum': 0.87306, 'weight_decay': 0.00092, 'warmup_epochs': 2.87513, 'warmup_momentum': 0.72297, 'box': 6.65392, 'cls': 0.33992, 'cls_pw': 0.00169, 'dfl': 1.55313, 'hsv_h': 0.01381, 'hsv_s': 0.9, 'hsv_v': 0.42446, 'degrees': 0.0088, 'translate': 0.17281, 'scale': 0.50068, 'shear': 0.0, 'perspective': 1e-05, 'flipud': 0.00729, 'fliplr': 0.49093, 'bgr': 0.00733, 'mosaic': 1.0, 'mixup': 0.0002, 'cutmix': 0.0, 'copy_paste': 0.0, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_fitness.png

Tuner: 10/20 iterations complete  (4356.85s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s
Tuner: Best fitness=0.85137 observed at iteration 7
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.9151, 'metrics/recall(B)': 0.93526, 'metrics/mAP50(B)': 0.96585, 'metrics/mAP50-95(B)': 0.85137, 'val/box_loss': 0.37397, 'val/cls_loss': 0.26148, 'val/dfl_loss': 0.00245, 'fitness': 0.85137}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\weights
Printing 'C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.97292
weight_decay: 0.00087
warmup_epochs: 2.6614
warmup_momentum: 0.95
box: 5.82995
cls: 0.41902
cls_pw: 0.00249
dfl: 1.50655
hsv_h: 0.01865
hsv_s: 0.89924
hsv_v: 0.382
degrees: 0.01146
translate: 0.16207
scale: 0.49959
shear: 0.00049
perspective: 1.0e-05
flipud: 0.00903
fliplr: 0.64909
bgr: 0.00299
mosaic: 1.0
mixup: 8.0e-05
cutmix: 0.0
copy_paste: 0.00455
close_mosaic: 10

Tuner: Starting iteration 11/20 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01229, 'momentum': 0.98, 'weight_decay': 0.00089, 'warmup_epochs': 2.99632, 'warmup_momentum': 0.68883, 'box': 7.09877, 'cls': 0.39891, 'cls_pw': 0.00178, 'dfl': 1.58377, 'hsv_h': 0.01569, 'hsv_s': 0.9, 'hsv_v': 0.36978, 'degrees': 0.01299, 'translate': 0.16553, 'scale': 0.4035, 'shear': 0.00086, 'perspective': 0.0, 'flipud': 0.00104, 'fliplr': 0.4882, 'bgr': 0.00197, 'mosaic': 0.92148, 'mixup': 0.0003, 'cutmix': 0.00853, 'copy_paste': 0.00284, 'close_mosaic': 10}
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_scatter_plots.png
Saved C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\tune_fitness.png

Tuner: 11/20 iterations complete  (4791.59s)
Tuner: Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s
Tuner: Best fitness=0.85883 observed at iteration 11
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.93953, 'metrics/recall(B)': 0.93015, 'metrics/mAP50(B)': 0.96751, 'metrics/mAP50-95(B)': 0.85883, 'val/box_loss': 0.4393, 'val/cls_loss': 0.23892, 'val/dfl_loss': 0.00246, 'fitness': 0.85883}
Tuner: Best fitness model is C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tune_v26s\weights

## 5. Full Training

### 5.1 Hyperparameters

Define once and reuse across all training runs.

In [15]:
# v8 tuning results
with open("runs/detect/tune_v8s/best_hyperparameters.yaml") as f:
    best_hps = yaml.safe_load(f)

# v11 tuning results
with open("runs/detect/tune_v11s/best_hyperparameters.yaml") as f:
    best_hps_v11 = yaml.safe_load(f)

# v26 tuning results
with open("runs/detect/tune_v26s/best_hyperparameters.yaml") as f:
    best_hps_v26 = yaml.safe_load(f)

In [16]:
# Fixed settings that tuning doesn't control — always override
FIXED = dict(
    data="./data.yaml",
    epochs=150,
    patience=20,
    imgsz=640,
    batch=16,
    seed=42,
    device=0,
    workers=4,
    cache="disk",
    amp=True,
    val=True,
    save_period=10,
    # Logo-safe augmentation overrides
    fliplr=0.0,
    flipud=0.0,
    mixup=0.0,
    cutmix=0.0,
    copy_paste=0.0,
    cls_pw=1.0,
)

# Tuned params as base, fixed settings take priority
TUNED_HPS = {**best_hps, **FIXED}
TUNED_HPS_V11 = {**best_hps_v11, **FIXED}
TUNED_HPS_V26 = {**best_hps_v26, **FIXED}

### 5.2 YOLOv8s Tuned 
Primary tuned model, full 150-epoch run.

In [6]:
model = YOLO("yolov8s.pt")
model.train(**TUNED_HPS, name="tuned_yolov8s")

New https://pypi.org/project/ultralytics/8.4.48 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.48753, cache=disk, cfg=None, classes=None, close_mosaic=9, cls=0.49308, cls_pw=1.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=./data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.50502, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=150, erasing=0.4, exist_ok=False, fliplr=0.0, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.00983, hsv_s=0.59554, hsv_v=0.40887, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.00429, lrf=0.0155, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.91496, mosaic=0.97172, multi_scale=0.0, name=tuned_yolov8s, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolov8s, save_frames=False, save_json=False, save_period=10, save_txt=False, scale=0.50368, seed=42, shear=0.01323, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.08416, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0032, warmup_momentum=0.793, weight_decay=0.001, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=8

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119144  ultralytics.nn.modules.head.Detect           [8, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,138,696 parameters, 11,138,680 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 261.164.3 MB/s, size: 205.3 KB)
train: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\train.cache... 1445 images, 139 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1445/1445 319.0Mit/s 0.0s
train: Caching images (3.7GB Disk): 100% ━━━━━━━━━━━━ 1445/1445 655.6it/s 2.2s0.1s
val: Fast image access  (ping: 0.10.0 ms, read: 293.359.6 MB/s, size: 259.7 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 116.7Mit/s 0.0s
val: Caching images (1.1GB Disk): 100% ━━━━━━━━━━━━ 334/334 409.4it/s 0.8s0.1s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.00429' and 'momentum=0.91496' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000833, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.001), 63 bias(decay=0.0)
Class weights: [      0.848       0.978       1.056       0.804       0.847       1.277        0.83       1.359]
Plotting labels to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolov8s\labels.jpg...
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolov8s
Starting training for 150 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/150      3.64G      1.089      2.239      1.115         19        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.7s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.1s0.3s
                   all        334        992      0.688      0.844      0.859      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/150      3.43G     0.7233      0.971     0.9521         17        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992       0.82      0.853      0.917      0.763

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/150      3.41G     0.6517     0.7918     0.9182         15        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.5s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.863      0.886      0.951      0.797

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/150      3.43G      0.637     0.7357     0.9181         25        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.6s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.861      0.919      0.955      0.815

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/150      3.41G     0.5834     0.6199     0.8888         26        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.867      0.939      0.962       0.83

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/150      3.44G     0.5468     0.5724      0.877         20        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 31.4s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.913      0.918      0.956      0.833

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/150       3.4G     0.5383     0.5383     0.8725         27        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 31.4s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.892      0.922      0.949      0.835

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/150      3.41G     0.5135     0.5496     0.8703         25        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.891       0.93      0.958      0.859

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/150      3.44G     0.4894     0.5116     0.8677         33        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 31.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.923      0.936      0.968      0.875

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/150      3.43G     0.4745     0.5002     0.8534         31        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 31.6s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.895      0.919      0.957      0.853

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/150      3.43G     0.4688     0.4652     0.8529         14        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 31.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992       0.94      0.938      0.967      0.884

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/150      3.43G     0.4504     0.4337      0.849         25        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 31.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.936      0.946      0.962      0.885

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/150      3.38G     0.4439     0.4349     0.8458         24        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.952      0.948      0.977        0.9

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/150      3.43G     0.4277     0.4104     0.8413         18        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.4s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.959      0.958      0.976      0.898

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/150       3.4G     0.4261     0.4171     0.8419         27        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.941      0.958      0.982      0.909

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/150      3.42G      0.411     0.4204     0.8379          8        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 31.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.957      0.958      0.982       0.91

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/150      3.42G     0.4228     0.4165     0.8394         22        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 31.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.942      0.949      0.973      0.893

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/150      3.43G     0.4062     0.3997     0.8353         22        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 31.5s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.7s0.3s
                   all        334        992      0.946      0.946      0.973      0.896

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/150      3.57G     0.3919     0.3804     0.8311         20        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.954      0.967      0.983      0.922

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/150       3.4G     0.3916     0.3801     0.8315         18        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 30.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.7s0.3s
                   all        334        992      0.943      0.956      0.981      0.919

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/150       3.4G     0.3898     0.3744     0.8301         16        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.952      0.934      0.966        0.9

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/150      3.42G     0.3751     0.3553     0.8266         16        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992       0.95      0.937      0.973      0.908

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/150      3.54G     0.3644     0.3555      0.827         23        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.1it/s 2.7s0.3s
                   all        334        992      0.974       0.96      0.985      0.924

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/150       3.4G     0.3665     0.3583     0.8283         29        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.962      0.972      0.982      0.918

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/150      3.39G     0.3617     0.3399      0.823         35        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.969      0.958      0.983      0.925

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/150      3.46G     0.3627     0.3448     0.8252         24        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.959      0.956      0.982      0.921

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/150      3.41G     0.3559     0.3313     0.8185         13        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.9s0.3s
                   all        334        992      0.961      0.968      0.984      0.924

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/150      3.42G     0.3514     0.3297     0.8252         15        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.963      0.955      0.982      0.925

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/150      3.41G     0.3504     0.3304      0.823         38        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.948      0.957      0.975      0.915

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/150      3.43G     0.3366     0.3269     0.8207         25        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.977       0.97      0.989      0.938

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/150       3.4G     0.3421     0.3153     0.8183         25        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.1it/s 2.7s0.3s
                   all        334        992      0.961       0.97      0.983      0.923

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/150      3.43G     0.3334     0.3025     0.8195         23        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.8s0.3s
                   all        334        992      0.965      0.971      0.983      0.933

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/150      3.44G     0.3277     0.3079     0.8202         19        640: 100% ━━━━━━━━━━━━ 91/91 3.0it/s 30.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.7s0.3s
                   all        334        992      0.963      0.964       0.98      0.933

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6, 7])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x000002BA969991D0>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,     0.96774,     0.96774,           0],
       [          1,           1,           1, ...,     0.94872,     0.94872,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       ...,
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,     0.96711,     0.96711,           0],
       [          1,           1,           1, ...,     0.57143,     0.57143,           0]], shape=(8, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

In [7]:
tuned_yolov8s = YOLO("runs/detect/tuned_yolov8s/weights/best.pt")

### 5.4 YOLOv8m — Medium

Larger backbone (~26M params vs ~11M for small). May offer better precision on complex logo appearances,
but requires more memory and is slower to train and infer.

In [ ]:
model = YOLO("yolov8m.pt")
model.train(**TUNED_HPS, name="tuned_yolov8m")

In [27]:
model = YOLO("runs/detect/tuned_yolov8m/weights/last.pt")

model.train(resume=True)

New https://pypi.org/project/ultralytics/8.4.49 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.48753, cache=disk, cfg=None, classes=None, close_mosaic=9, cls=0.49308, cls_pw=1.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.50502, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=150, erasing=0.4, exist_ok=False, fliplr=0.0, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.00983, hsv_s=0.59554, hsv_v=0.40887, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.00429, lrf=0.0155, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=runs\detect\tuned_yolov8m\weights\last.pt, momentum=0.91496, mosaic=0.97172, multi_scale=0.0, name=tuned_yolov8m, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=runs\detect\tuned_yolov8m\weights\last.pt, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolov8m, save_frames=False, save_json=False, save_period=10, save_txt=False, scale=0.50368, seed=42, shear=0.01323, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.08416, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.0, warmup_epochs=3.0032, warmup_momentum=0.793, weight_decay=0.001, workers=4, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3780328  ultralytics.nn.modules.head.Detect           [8, 16, None, [192, 384, 576]]
Model summary: 170 layers, 25,860,952 parameters, 25,860,936 gradients, 79.1 GFLOPs

Transferred 475/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 291.179.9 MB/s, size: 216.9 KB)
train: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\train.cache... 1445 images, 139 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1445/1445 606.1Mit/s 0.0s
train: Caching images (3.7GB Disk): 100% ━━━━━━━━━━━━ 1445/1445 20.4Kit/s 0.1s
val: Fast image access  (ping: 0.10.0 ms, read: 78.240.3 MB/s, size: 362.6 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 155.7Mit/s 0.0s
val: Caching images (1.1GB Disk): 100% ━━━━━━━━━━━━ 334/334 17.4Kit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.00429' and 'momentum=0.91496' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000833, momentum=0.9) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Class weights: [      0.848       0.978       1.056       0.804       0.847       1.277        0.83       1.359]
Plotting labels to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolov8m\labels.jpg...
Resuming training runs\detect\tuned_yolov8m\weights\last.pt from epoch 95 to 150 total epochs
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolov8m
Starting training for 150 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     95/150      6.42G     0.1901     0.1666     0.7987         19        640: 100% ━━━━━━━━━━━━ 91/91 4.0s/it 6:082.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.5s0.5s
                   all        334        992      0.984      0.976       0.99      0.965

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     96/150      6.55G     0.1885     0.1629     0.7987         17        640: 100% ━━━━━━━━━━━━ 91/91 3.3s/it 4:571.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992      0.973      0.983       0.99      0.967

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     97/150      6.55G     0.1833     0.1531     0.7918         15        640: 100% ━━━━━━━━━━━━ 91/91 2.1s/it 3:131.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.3s0.5s
                   all        334        992      0.974      0.983      0.991      0.966

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     98/150      6.49G      0.189      0.166     0.8022         25        640: 100% ━━━━━━━━━━━━ 91/91 2.1s/it 3:131.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992       0.98      0.965      0.985      0.961

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     99/150      6.55G     0.1847     0.1547     0.7955         26        640: 100% ━━━━━━━━━━━━ 91/91 2.2s/it 3:191.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992      0.981      0.973      0.991      0.968

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    100/150      6.55G     0.1776     0.1535     0.7957         20        640: 100% ━━━━━━━━━━━━ 91/91 1.7s/it 2:351.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.3s0.5s
                   all        334        992      0.977      0.979      0.987      0.965

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    101/150      6.57G     0.1819     0.1529     0.7968         27        640: 100% ━━━━━━━━━━━━ 91/91 2.5s/it 3:482.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.3s0.5s
                   all        334        992      0.987      0.976      0.988      0.964

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    102/150      6.47G     0.1821     0.1536     0.8006         25        640: 100% ━━━━━━━━━━━━ 91/91 1.9s/it 2:571.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.3s0.5s
                   all        334        992      0.974      0.973      0.983      0.962

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    103/150      6.59G     0.1767     0.1513     0.7995         33        640: 100% ━━━━━━━━━━━━ 91/91 1.6s/it 2:241.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.3s0.5s
                   all        334        992      0.976      0.977      0.985      0.961

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    104/150      6.55G      0.176     0.1491     0.7972         31        640: 100% ━━━━━━━━━━━━ 91/91 1.5s/it 2:161.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.2s0.5s
                   all        334        992      0.982      0.975      0.985      0.962

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    105/150       6.6G      0.176     0.1511     0.7993         14        640: 100% ━━━━━━━━━━━━ 91/91 2.1s/it 3:091.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992      0.974      0.974      0.983      0.958

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    106/150      6.47G     0.1724     0.1464     0.7943         25        640: 100% ━━━━━━━━━━━━ 91/91 2.1s/it 3:121.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.4s0.5s
                   all        334        992      0.981      0.977      0.988      0.964

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    107/150      6.57G     0.1769     0.1517     0.7935         24        640: 100% ━━━━━━━━━━━━ 91/91 2.4s/it 3:381.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992       0.98      0.973      0.985      0.963

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    108/150      6.55G     0.1742     0.1514      0.792         18        640: 100% ━━━━━━━━━━━━ 91/91 1.9s/it 2:561.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992      0.978      0.983      0.989      0.968

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    109/150      6.56G     0.1726     0.1467     0.7999         27        640: 100% ━━━━━━━━━━━━ 91/91 2.3s/it 3:331.9ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992      0.979      0.978      0.985      0.963

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    110/150      6.44G     0.1714     0.1486     0.7942          8        640: 100% ━━━━━━━━━━━━ 91/91 2.2s/it 3:201.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.3s0.5s
                   all        334        992      0.981      0.973      0.988      0.965

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    111/150      6.55G     0.1742     0.1515     0.7943         22        640: 100% ━━━━━━━━━━━━ 91/91 3.3s/it 5:051.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 1.9it/s 5.7s0.5s
                   all        334        992      0.984      0.982       0.99      0.969

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    112/150      6.56G     0.1706     0.1492     0.7929         22        640: 100% ━━━━━━━━━━━━ 91/91 2.4s/it 3:381.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.3s0.5s
                   all        334        992      0.982      0.979      0.988      0.967

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    113/150      6.58G     0.1656       0.14     0.7921         20        640: 100% ━━━━━━━━━━━━ 91/91 1.6s/it 2:241.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992      0.983      0.976      0.989      0.969

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    114/150      6.45G     0.1731     0.1512     0.7928         18        640: 100% ━━━━━━━━━━━━ 91/91 2.3s/it 3:311.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992      0.974       0.98       0.99      0.967

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    115/150      6.55G      0.164     0.1415     0.7945         16        640: 100% ━━━━━━━━━━━━ 91/91 2.7s/it 4:031.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992      0.976      0.977      0.991      0.969

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    116/150      6.53G      0.164     0.1396      0.792         16        640: 100% ━━━━━━━━━━━━ 91/91 1.9s/it 2:571.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992       0.98      0.983       0.99       0.97

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    117/150      6.57G     0.1586     0.1352     0.7958         23        640: 100% ━━━━━━━━━━━━ 91/91 2.1s/it 3:082.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.3s0.5s
                   all        334        992      0.982      0.975      0.988      0.967

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    118/150      6.44G     0.1643     0.1421      0.797         29        640: 100% ━━━━━━━━━━━━ 91/91 2.1s/it 3:071.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.3s0.5s
                   all        334        992      0.974      0.976      0.985      0.963

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    119/150      6.54G     0.1603     0.1349     0.7886         35        640: 100% ━━━━━━━━━━━━ 91/91 2.3s/it 3:301.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992      0.977      0.972      0.986      0.965

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    120/150      6.56G     0.1609     0.1392     0.7955         24        640: 100% ━━━━━━━━━━━━ 91/91 1.9s/it 2:521.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.2it/s 5.1s0.5s
                   all        334        992      0.982      0.974      0.988      0.965

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    121/150       6.6G     0.1574      0.136     0.7926         13        640: 100% ━━━━━━━━━━━━ 91/91 1.9s/it 2:501.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992      0.973      0.982      0.986      0.965

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    122/150      6.47G     0.1583     0.1325     0.7918         15        640: 100% ━━━━━━━━━━━━ 91/91 2.1s/it 3:101.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.1it/s 5.4s0.5s
                   all        334        992      0.977      0.981      0.987      0.966

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    123/150      6.56G     0.1601     0.1368     0.7973         38        640: 100% ━━━━━━━━━━━━ 91/91 1.7s/it 2:381.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.5s0.5s
                   all        334        992      0.978      0.984      0.988      0.969

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    124/150      6.54G     0.1531     0.1322     0.7903         25        640: 100% ━━━━━━━━━━━━ 91/91 2.2s/it 3:251.9ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 1.9it/s 5.9s0.5s
                   all        334        992      0.983      0.979      0.989      0.968

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    125/150      6.56G     0.1561     0.1319       0.79         25        640: 100% ━━━━━━━━━━━━ 91/91 3.8s/it 5:492.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.6s0.5s
                   all        334        992      0.971       0.98      0.986      0.965

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    126/150      6.49G     0.1552     0.1297     0.7914         23        640: 100% ━━━━━━━━━━━━ 91/91 2.7s/it 4:061.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 1.9it/s 5.7s0.5s
                   all        334        992      0.978      0.976      0.986      0.967

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    127/150      6.57G     0.1545     0.1299     0.7975         19        640: 100% ━━━━━━━━━━━━ 91/91 3.2s/it 4:501.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.0it/s 5.4s0.5s
                   all        334        992      0.973      0.985      0.984      0.963


ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6, 7])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x000002BAA1AD4050>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,     0.98684,     0.98684,           0],
       [          1,           1,           1, ...,           1,           1,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       ...,
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,        0.98,        0.98,           0],
       [          1,           1,           1, ...,           0,           0,           0]], shape=(8, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

In [28]:
tuned_yolov8m = YOLO("runs/detect/tuned_yolov8m/weights/best.pt")

### 5.5 YOLOv11s

YOLOv11 is an update in the Ultralytics family (released late 2024).
It uses an updated C3k2 backbone and SPPF improvements, offering better accuracy per parameter
compared to YOLOv8 at similar model sizes.

In [17]:
model = YOLO("yolo11s.pt")
model.train(**TUNED_HPS_V11, name="tuned_yolo11s")

New https://pypi.org/project/ultralytics/8.4.49 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=disk, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=1.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=./data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=150, erasing=0.4, exist_ok=False, fliplr=0.0, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=tuned_yolo11s, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolo11s, save_frames=False, save_json=False, save_period=10, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=8

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    822504  ultralytics.nn.modules.head.Detect           [8, 16, None, [128, 256, 512]]
YOLO11s summary: 182 layers, 9,430,888 parameters, 9,430,872 gradients, 21.6 GFLOPs

Transferred 493/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 236.259.6 MB/s, size: 216.9 KB)
train: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\train.cache... 1445 images, 139 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1445/1445 505.1Mit/s 0.0s
train: Caching images (3.7GB Disk): 100% ━━━━━━━━━━━━ 1445/1445 20.1Kit/s 0.1s
val: Fast image access  (ping: 0.10.0 ms, read: 311.598.6 MB/s, size: 362.6 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 116.7Mit/s 0.0s
val: Caching images (1.1GB Disk): 100% ━━━━━━━━━━━━ 334/334 14.8Kit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000833, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Class weights: [      0.848       0.978       1.056       0.804       0.847       1.277        0.83       1.359]
Plotting labels to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolo11s\labels.jpg...
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolo11s
Starting training for 150 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/150      4.02G      1.046      2.016      1.047         28        640: 100% ━━━━━━━━━━━━ 91/91 2.0it/s 46.3s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 1.3s/it 13.8s0.4s
                   all        334        992      0.762      0.834      0.853      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/150      4.06G     0.7212     0.9159     0.9268         17        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992      0.855      0.815      0.892      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/150      4.04G     0.6792     0.7716     0.9071         24        640: 100% ━━━━━━━━━━━━ 91/91 2.9it/s 31.4s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 4.0it/s 2.8s0.3s
                   all        334        992      0.891       0.88      0.935      0.795

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/150      4.07G     0.6281     0.6928      0.897         24        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.6s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.893      0.863      0.915      0.779

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/150      4.06G     0.6002     0.6352     0.8881         21        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992        0.9      0.896      0.946      0.813

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/150      4.09G     0.5746     0.6173     0.8811         27        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.8s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.863      0.923      0.943      0.811

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/150      4.05G     0.5428     0.5566     0.8751          7        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.927      0.923      0.961      0.856

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/150      4.06G     0.5221     0.5189     0.8686         12        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.936      0.912      0.959       0.86

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/150      4.05G     0.4986     0.5104      0.864         37        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.7s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.938      0.917      0.958      0.857

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/150      4.07G     0.4988     0.5074     0.8609         23        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.9s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.933      0.918      0.953      0.862

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/150      4.05G     0.4715     0.4694     0.8476         28        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.6s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.939      0.946      0.966       0.88

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/150      4.07G     0.4666     0.4723     0.8489         18        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992       0.92      0.895      0.949       0.85

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/150      4.05G     0.4655     0.4631     0.8468         14        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 33.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.944      0.943      0.975      0.893

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/150      4.06G     0.4398     0.4432     0.8423         34        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.8s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.927      0.912      0.949      0.874

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/150      4.05G     0.4397     0.4423     0.8407         31        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.943      0.935      0.976      0.895

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/150      4.07G     0.4363     0.4531     0.8402         34        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.941      0.938      0.962      0.864

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/150      4.05G     0.4264     0.4208     0.8336         33        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.941       0.97      0.979      0.912

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/150      4.07G     0.4089     0.4003     0.8343         14        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.9s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992       0.94      0.923      0.966      0.904

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/150      4.05G     0.4017     0.4024     0.8316         24        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992       0.94      0.953      0.978      0.918

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/150       4.1G     0.3936     0.3912     0.8325         15        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.945       0.94      0.975      0.902

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/150      4.06G     0.3907     0.3845     0.8314         18        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 33.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.939      0.944      0.977      0.919

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/150      4.06G     0.3934     0.3853      0.832         27        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.9s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.9it/s 2.9s0.3s
                   all        334        992      0.953      0.938      0.975      0.921

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/150      4.09G     0.3806     0.3787     0.8263         19        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.5s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.964      0.951      0.985      0.933

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/150      4.07G     0.3862     0.3768     0.8267         21        640: 100% ━━━━━━━━━━━━ 91/91 2.7it/s 33.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 2.9s0.3s
                   all        334        992      0.957      0.964       0.98      0.921

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/150      4.06G     0.3702     0.3669      0.822         39        640: 100% ━━━━━━━━━━━━ 91/91 2.7it/s 33.2s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.947      0.953      0.982      0.923

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/150       4.1G     0.3615     0.3656     0.8166         26        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 33.1s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.952      0.944      0.979      0.928

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/150      4.06G     0.3651     0.3684      0.826         30        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.941      0.959      0.977      0.917

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/150      4.07G     0.3714     0.3683     0.8225         19        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.956      0.955      0.981      0.926

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/150      4.05G     0.3593     0.3588     0.8245         30        640: 100% ━━━━━━━━━━━━ 91/91 2.7it/s 33.1s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 2.9s0.3s
                   all        334        992      0.939      0.963      0.981      0.932

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/150      4.07G     0.3497     0.3489      0.819         32        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.8s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.969       0.95      0.981      0.935

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/150      4.08G     0.3463     0.3344     0.8165         11        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 33.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.962      0.952      0.978      0.933

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/150      4.07G     0.3405     0.3289     0.8172         19        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 33.0s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.968      0.956      0.982      0.935

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/150      4.07G     0.3396     0.3383     0.8151         19        640: 100% ━━━━━━━━━━━━ 91/91 2.8it/s 32.8s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.952      0.947      0.976      0.934


ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6, 7])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x000002BAB0D26190>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,     0.96154,     0.96154,           0],
       [          1,           1,           1, ...,      0.9569,      0.9569,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       ...,
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,        0.98,        0.98,           0],
       [          1,           1,           1, ...,     0.63309,     0.63309,           0]], shape=(8, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

In [18]:
tuned_yolo11s = YOLO("runs/detect/tuned_yolo11s/weights/best.pt")

### 5.6 YOLOv26s

Latest YOLO model

In [19]:
model = YOLO("yolo26s.pt")
model.train(**TUNED_HPS_V26, name="tuned_yolo26s")

New https://pypi.org/project/ultralytics/8.4.49 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.00443, box=5.78288, cache=disk, cfg=None, classes=None, close_mosaic=8, cls=0.42553, cls_pw=1.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=./data.yaml, degrees=0.01023, deterministic=True, device=0, dfl=1.43178, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=150, erasing=0.4, exist_ok=False, fliplr=0.0, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.01552, hsv_s=0.71166, hsv_v=0.49503, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.00943, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26s.pt, momentum=0.98, mosaic=0.98824, multi_scale=0.0, name=tuned_yolo26s, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolo26s, save_frames=False, save_json=False, save_period=10, save_txt=False, scale=0.34998, seed=42, shear=0.00064, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.16213, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=2.86383, warmup_momentum=0.78833, weight_decay=0.00088, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=8

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    477184  ultralytics.nn.modules.block.C3k2            [768, 256, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    136192  ultralytics.nn.modules.block.C3k2            [512, 128, 1, True]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1843712  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1    938056  ultralytics.nn.modules.head.Detect           [8, 1, True, [128, 256, 512]]
YOLO26s summary: 260 layers, 9,954,056 parameters, 9,954,056 gradients, 22.5 GFLOPs

Transferred 696/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 274.180.9 MB/s, size: 216.9 KB)
train: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\train.cache... 1445 images, 139 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1445/1445 551.0Mit/s 0.0s
train: Caching images (3.7GB Disk): 100% ━━━━━━━━━━━━ 1445/1445 19.9Kit/s 0.1s
val: Fast image access  (ping: 0.10.0 ms, read: 306.172.1 MB/s, size: 362.6 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 100.1Mit/s 0.0s
val: Caching images (1.1GB Disk): 100% ━━━━━━━━━━━━ 334/334 11.5Kit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.00943' and 'momentum=0.98' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000833, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.00088), 126 bias(decay=0.0)
Class weights: [      0.848       0.978       1.056       0.804       0.847       1.277        0.83       1.359]
Plotting labels to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolo26s\labels.jpg...
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\tuned_yolo26s
Starting training for 150 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/150      4.97G      0.828      4.912   0.005302         21        640: 100% ━━━━━━━━━━━━ 91/91 2.1it/s 44.1s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.9it/s 3.8s0.3s
                   all        334        992      0.548      0.727      0.634      0.526

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/150      4.86G     0.6399      1.358   0.003918         23        640: 100% ━━━━━━━━━━━━ 91/91 2.3it/s 39.2s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.1s0.3s
                   all        334        992      0.741      0.791      0.813      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/150      4.86G      0.603     0.8812   0.003669         18        640: 100% ━━━━━━━━━━━━ 91/91 2.3it/s 38.9s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 2.8it/s 3.9s0.4s
                   all        334        992      0.848      0.827      0.896       0.74

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/150      4.84G     0.5599     0.6934   0.003407         10        640: 100% ━━━━━━━━━━━━ 91/91 2.3it/s 38.8s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.4it/s 3.3s0.3s
                   all        334        992      0.869      0.868      0.916      0.781

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/150      4.85G     0.5326     0.6075   0.003171         21        640: 100% ━━━━━━━━━━━━ 91/91 2.3it/s 38.7s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.1s0.3s
                   all        334        992      0.883      0.873      0.921      0.784

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/150      4.82G     0.4938     0.5459   0.002941         15        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.7s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.0s0.3s
                   all        334        992      0.847      0.888      0.916      0.797

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/150      4.84G     0.4928     0.5313   0.002899         19        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.5s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992      0.867      0.879      0.924      0.798

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/150      4.82G     0.4654     0.4416   0.002826         21        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.2s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992      0.882      0.892      0.932       0.82

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/150      4.86G     0.4418     0.4288   0.002635         22        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.4s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.0s0.3s
                   all        334        992        0.9      0.926      0.955      0.841

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/150      4.82G     0.4371     0.4301   0.002632         24        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.7s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.0s0.3s
                   all        334        992      0.919      0.917      0.958      0.852

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/150      4.84G     0.4209     0.3742   0.002483         26        640: 100% ━━━━━━━━━━━━ 91/91 2.3it/s 38.7s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.0s0.3s
                   all        334        992      0.925      0.918      0.948      0.858

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/150      4.84G     0.4032     0.3727   0.002386         15        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.6s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.0s0.3s
                   all        334        992      0.932      0.903      0.956      0.862

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/150      4.84G     0.3909     0.3498   0.002308         25        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.4s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.0s0.3s
                   all        334        992      0.925      0.908      0.949      0.853

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/150      4.84G     0.3955     0.3802    0.00232         31        640: 100% ━━━━━━━━━━━━ 91/91 2.3it/s 38.8s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.1s0.3s
                   all        334        992      0.917      0.903      0.949      0.854

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/150      4.86G     0.3884     0.3396   0.002296         16        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.6s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992      0.925      0.923      0.957      0.874

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/150      4.83G     0.3807     0.3439   0.002246         14        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.5s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.1s0.3s
                   all        334        992       0.94       0.93      0.964       0.88

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/150      4.83G     0.3895     0.3358   0.002271         13        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.6s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992      0.927      0.922       0.95      0.859

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/150      4.82G     0.3761     0.3086   0.002198         21        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.4s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992      0.934      0.924      0.969      0.894

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/150      4.83G     0.3608     0.3154   0.002088         22        640: 100% ━━━━━━━━━━━━ 91/91 2.3it/s 38.8s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992      0.943      0.933      0.963      0.891

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/150      4.82G     0.3536     0.2989   0.002083          7        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.6s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992       0.94      0.918      0.967      0.884

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/150      4.85G     0.3464     0.3012   0.002002         33        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.7s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.1s0.3s
                   all        334        992       0.93      0.937      0.967        0.9

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/150      4.83G     0.3619     0.3193   0.002082         26        640: 100% ━━━━━━━━━━━━ 91/91 2.3it/s 39.0s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992       0.95      0.913      0.963      0.891

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/150      4.87G     0.3427     0.2773   0.002011         27        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.0s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992      0.916      0.941      0.968      0.895

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/150      4.82G     0.3396     0.2852   0.001995         19        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 38.1s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992       0.92      0.944      0.968      0.897

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/150      4.83G     0.3471     0.2844   0.001986         27        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 37.2s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.0s0.3s
                   all        334        992      0.944      0.949      0.973      0.896

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/150      4.83G       0.33     0.2529   0.001926         23        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 37.5s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.0s0.3s
                   all        334        992      0.946      0.949      0.975      0.901

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/150      4.84G     0.3216     0.2514   0.001866         33        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 37.5s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.0s0.3s
                   all        334        992      0.946      0.946      0.973      0.913

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/150      4.82G     0.3118     0.2514   0.001797         20        640: 100% ━━━━━━━━━━━━ 91/91 2.5it/s 37.0s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.949      0.933      0.973      0.919

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/150      4.87G     0.3067     0.2351   0.001767         18        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 37.5s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.8it/s 2.9s0.3s
                   all        334        992      0.934      0.953      0.971      0.922

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/150      4.84G     0.3132     0.2702   0.001797         26        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 37.6s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992      0.948      0.942      0.973       0.91

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/150      4.86G     0.3188      0.241   0.001827         28        640: 100% ━━━━━━━━━━━━ 91/91 2.3it/s 38.9s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.6it/s 3.1s0.3s
                   all        334        992       0.94      0.942      0.972      0.909

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/150      4.81G     0.3032     0.2399   0.001737         31        640: 100% ━━━━━━━━━━━━ 91/91 2.4it/s 37.2s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992      0.948      0.941      0.975      0.923

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/150      4.84G     0.3043     0.2303   0.001726         24        640: 100% ━━━━━━━━━━━━ 91/91 2.5it/s 37.1s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 3.7it/s 3.0s0.3s
                   all        334        992       0.95      0.936      0.966      0.905


ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6, 7])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x000002BAA1610050>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,     0.98039,     0.98039,           0],
       [          1,           1,           1, ...,     0.93277,     0.93277,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       ...,
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,     0.97351,     0.97351,           0],
       [          1,           1,           1, ...,      0.6069,      0.6069,           0]], shape=(8, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

In [20]:
tuned_yolo26s = YOLO("runs/detect/tuned_yolo26s/weights/best.pt")

## 6. Evaluation

We evaluate all models on both the **validation** and **test** sets.
- **Val set** — used during training for early stopping; results here may be slightly optimistic
- **Test set** — held-out; the true measure of generalisation

Metrics collected: `mAP50`, `mAP50-95`, `Precision`, `Recall`.

In [21]:
os.makedirs("./results", exist_ok=True)

def get_metrics(model, name, split):
    """Evaluate a model on a given split and return overall + per-class DataFrames."""
    metrics = model.val(
        data="./data.yaml",
        plots=True,
        save=True,
        save_json=True,
        project="./results",
        name=f"{name}_{split}",
        split=split,
        verbose=False
    )

    overall_df = pd.DataFrame({
        "mAP50":     [metrics.box.map50],
        "mAP50-95":  [metrics.box.map],
        "Precision": [metrics.box.mp],
        "Recall":    [metrics.box.mr]
    })

    per_class_rows = []
    for i, class_name in metrics.names.items():
        p, r, ap50, ap = metrics.box.class_result(i)
        per_class_rows.append({
            "Class": class_name,
            "Precision": p,
            "Recall": r,
            "mAP50": ap50,
            "mAP50-95": ap
        })

    return overall_df, pd.DataFrame(per_class_rows)

### 6.1 Evaluate on Test Set

In [29]:
# Map of display name  loaded model
models = {
    "Baseline YOLOv8n":      baseline_yolov8n,
    "Tuned YOLOv8s":         tuned_yolov8s,
    "Tuned YOLOv8m":         tuned_yolov8m,
    "Tuned YOLOv11s":        tuned_yolo11s,
    "Tuned YOLOv26s":        tuned_yolo26s,
}

test_overall = {}
test_per_class = {}

for name, mdl in models.items():
    safe_name = name.lower().replace(" ", "_")
    overall, per_class = get_metrics(mdl, safe_name, "test")
    test_overall[name] = overall
    test_per_class[name] = per_class
    print(f"Done: {name}")

Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 218.542.3 MB/s, size: 175.1 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\test.cache... 320 images, 30 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 320/320 167.8Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 20/20 4.7it/s 4.2s0.2s
                   all        320        923      0.943      0.964       0.98      0.933
Speed: 3.9ms preprocess, 4.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\baseline_yolov8n_test2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\baseline_yolov8n_test2
Done: Baseline YOLOv8n
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1346.3709.0 MB/s, size: 234.0 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\test.cache... 320 images, 30 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 320/320 134.2Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 20/20 4.2it/s 4.7s0.2s
                   all        320        923      0.953      0.977      0.987      0.963
Speed: 1.0ms preprocess, 9.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov8s_test2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov8s_test2
Done: Tuned YOLOv8s
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
Model summary (fused): 93 layers, 25,844,392 parameters, 0 gradients, 78.7 GFLOPs
val: Fast image access  (ping: 0.10.0 ms, read: 1380.7773.7 MB/s, size: 241.1 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\test.cache... 320 images, 30 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 320/320 95.9Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 20/20 2.2it/s 9.0s0.5s
                   all        320        923      0.976      0.975      0.987      0.973
Speed: 1.6ms preprocess, 22.6ms inference, 0.0ms loss, 0.6ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov8m_test2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov8m_test2
Done: Tuned YOLOv8m
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.00.0 ms, read: 1417.0658.3 MB/s, size: 200.3 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\test.cache... 320 images, 30 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 320/320 134.2Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 20/20 4.1it/s 4.9s0.2s
                   all        320        923      0.972      0.964      0.985      0.967
Speed: 1.2ms preprocess, 9.6ms inference, 0.0ms loss, 0.9ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov11s_test2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov11s_test2
Done: Tuned YOLOv11s
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1527.0717.6 MB/s, size: 224.1 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\test.cache... 320 images, 30 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 320/320 122.0Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 20/20 4.2it/s 4.7s0.2s
                   all        320        923      0.981      0.962      0.983      0.967
Speed: 1.0ms preprocess, 9.8ms inference, 0.0ms loss, 0.2ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov26s_test2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov26s_test2
Done: Tuned YOLOv26s

### 6.2 Evaluate on Validation Set

In [30]:
val_overall = {}
val_per_class = {}

for name, mdl in models.items():
    safe_name = name.lower().replace(" ", "_")
    overall, per_class = get_metrics(mdl, safe_name, "val")
    val_overall[name] = overall
    val_per_class[name] = per_class
    print(f"Done: {name}")

Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)

val: Fast image access  (ping: 0.10.0 ms, read: 343.746.6 MB/s, size: 304.0 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 100.1Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 5.8it/s 3.6s0.2s
                   all        334        992      0.964      0.949      0.981      0.937
Speed: 1.6ms preprocess, 4.4ms inference, 0.0ms loss, 1.2ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\baseline_yolov8n_val2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\baseline_yolov8n_val2
Done: Baseline YOLOv8n
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 330.3307.6 MB/s, size: 488.0 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 155.7Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 4.1it/s 5.1s0.2s
                   all        334        992      0.977      0.974       0.99      0.962
Speed: 1.5ms preprocess, 9.3ms inference, 0.0ms loss, 0.8ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov8s_val2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov8s_val2
Done: Tuned YOLOv8s
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 290.777.8 MB/s, size: 254.8 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 127.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.2it/s 9.4s0.4s
                   all        334        992      0.982      0.979       0.99      0.972
Speed: 1.7ms preprocess, 22.4ms inference, 0.0ms loss, 0.7ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov8m_val2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov8m_val2
Done: Tuned YOLOv8m
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 313.3195.4 MB/s, size: 351.2 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 116.7Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 4.2it/s 5.0s0.2s
                   all        334        992      0.972      0.985      0.991      0.966
Speed: 1.6ms preprocess, 9.3ms inference, 0.0ms loss, 0.7ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov11s_val2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov11s_val2
Done: Tuned YOLOv11s
Ultralytics 8.4.38  Python-3.13.3 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3050, 6143MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 299.692.1 MB/s, size: 246.0 KB)
val: Scanning C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\data\labels\val.cache... 334 images, 27 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 334/334 93.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 4.1it/s 5.1s0.2s
                   all        334        992      0.981      0.971      0.987      0.962
Speed: 1.6ms preprocess, 9.8ms inference, 0.0ms loss, 0.2ms postprocess per image
Saving C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov26s_val2\predictions.json...
Results saved to C:\Users\user\Documents\DARLYN\SMARTech\pubmat-checker\training\runs\detect\results\tuned_yolov26s_val2
Done: Tuned YOLOv26s

### 6.3 Model Comparison Summary

Overall metrics for all models side-by-side.

In [31]:
def build_summary(overall_dict, split_label):
    df = pd.concat(overall_dict.values())
    df.index = overall_dict.keys()
    df["Split"] = split_label
    return df

summary_test = build_summary(test_overall, "Test")
summary_val  = build_summary(val_overall,  "Val")

combined = (
    pd.concat([summary_test, summary_val])
    .reset_index()
    .rename(columns={"index": "Model"})
    .set_index(["Model", "Split"])
    .round(4)
    .sort_index()
)


styled_combined = (
    combined.style
    .highlight_max(axis=0, color="#90EE90")
    .background_gradient(cmap="YlGn", axis=0)
    .format("{:.4f}")
)

styled_combined

styled_combined

In [ ]:

combined.to_csv("./results/model_comparison.csv")
print("Saved to ./results/model_comparison.csv")

### 6.4 Per-Class Breakdown

Inspect per-class performance for the best-performing model on the test set.
Low recall on a class may indicate insufficient training samples or ambiguous annotations.
Low precision may indicate visual confusion between classes (e.g. Correct vs Incorrect for the same brand).

In [25]:
best_model_name = "Tuned YOLOv8m"  

print(f"Per-Class Metrics — {best_model_name} (Test Set):")
test_per_class[best_model_name].set_index("Class").round(4)

Per-Class Metrics — Tuned YOLOv8m (Test Set):

                Precision  Recall   mAP50  mAP50-95
Class
NYC_Correct        0.9797  1.0000  0.9881    0.9881
NYC_Incorrect      0.9924  0.9911  0.9950    0.9794
BP_Correct         0.9248  1.0000  0.9851    0.9851
BP_Incorrect       0.9921  0.9600  0.9919    0.9698
SK_Correct         0.9517  1.0000  0.9905    0.9905
SK_Incorrect       0.9893  0.9627  0.9808    0.9392
YORP_Correct       0.9736  1.0000  0.9942    0.9941
YORP_Incorrect     0.9767  0.9739  0.9838    0.9153

In [26]:
print(f"Per-Class Metrics — {best_model_name} (Val Set):")
val_per_class[best_model_name].set_index("Class").round(4)

Per-Class Metrics — Tuned YOLOv8m (Val Set):

                Precision  Recall   mAP50  mAP50-95
Class
NYC_Correct        0.9868  0.9990  0.9949    0.9927
NYC_Incorrect      0.9982  0.9910  0.9950    0.9761
BP_Correct         0.9734  0.9922  0.9941    0.9876
BP_Incorrect       1.0000  0.9735  0.9946    0.9735
SK_Correct         0.9598  0.9929  0.9891    0.9818
SK_Incorrect       0.9879  0.9408  0.9836    0.9384
YORP_Correct       0.9799  0.9935  0.9927    0.9896
YORP_Incorrect     0.9882  0.9556  0.9855    0.9191

### 6.5 Export All Per-Class Results

In [ ]:
for name, df in test_per_class.items():
    safe = name.lower().replace(" ", "_")
    df.to_csv(f"./results/{safe}_per_class_test.csv", index=False)

for name, df in val_per_class.items():
    safe = name.lower().replace(" ", "_")
    df.to_csv(f"./results/{safe}_per_class_val.csv", index=False)

print("All per-class CSVs saved to ./results/")